#!/usr/bin/env python3
"""Diagrams for /email/.

Deliverability failures share a shape the other sections do not: the send succeeds.
SES returns a message ID, the API call is a 200, and the mail is discarded somewhere
you cannot see. So most of these problem chains end in a success response and a
silent drop, which is the whole reason the section exists.
"""
from diagrams import branch, chain

V = {

"email/ses-still-in-sandbox": dict(
  flow_intro="Sandbox is a state on the account, not an error on the send, so the script asks for the state directly. It reads the account's sending status and quota and tells you whether the address you are testing with is one of the verified identities that makes sandbox look like it is working.",
  diagram_problem=chain("sand-p",
    "Diagram of the problem. In the sandbox, a send to a verified address succeeds normally, so testing looks fine. The same call to any unverified address is rejected, and because tests only ever used verified addresses nobody discovers the limit until real customers are involved.",
    "Sandbox is invisible while you test, because you test with the addresses it allows.",
    [("Send to your own address", "verified identity"),
     ("SES", "accepts it, looks healthy"),
     ("Send to a customer", "unverified recipient"),
     ("Rejected", "limit found in production")],
    fail_at=2),
  diagram_fix=branch("sand-f",
    "Diagram of the fix. The account's sending state is read directly and sorted into production access, sandbox, or sending disabled after a review, each of which needs a different response.",
    "Three different states, one identical-looking test. Read the account, not the send result.",
    ("Read the account state", "GetAccount: enabled, quota, status"),
    [("Production access", "any recipient, quota applies", "good"),
     ("Sandbox", "verified recipients only. Request access", "bad"),
     ("Sending disabled", "a review already happened", "bad")]),
),

"email/ses-identity-verified-but-dkim-drifted": dict(
  flow_intro="A verified identity and working DKIM are two different facts, and the console shows the first prominently. The script queries the published CNAMEs for the selectors SES expects and compares them against what SES says it is signing with.",
  diagram_problem=chain("dkim-p",
    "Diagram of the problem. The identity still shows verified, but a DNS migration dropped the DKIM CNAME records. Mail still sends, arrives unsigned, and fails the receiver's DMARC alignment check, so it is filtered at the far end with nothing to see at the sending end.",
    "Verified is about the identity. Signed is about the records, and only one of them is on screen.",
    [("DNS migrated", "DKIM CNAMEs not carried over"),
     ("Identity", "still shows verified"),
     ("Mail sends", "unsigned"),
     ("Receiver", "DMARC fails, filtered")],
    fail_at=1),
  diagram_fix=branch("dkim-f",
    "Diagram of the fix. Each selector SES expects is resolved in DNS and compared against what SES reports, sorting the identity into signing correctly, mid-rotation, or publishing nothing at all.",
    "Resolve the selectors yourself. The verified badge will not tell you they are gone.",
    ("Resolve each selector", "compare DNS against what SES expects"),
    [("All selectors resolve", "signing correctly", "good"),
     ("Some resolve, some do not", "mid-rotation, finish it", "plain"),
     ("None resolve", "mail is going out unsigned", "bad")]),
),

"email/ses-mail-from-not-set": dict(
  flow_intro="Without a custom MAIL FROM domain, SES uses its own, which authenticates fine and does not align with your From header. The script reads the MAIL FROM attributes and the DNS behind them, so an unaligned SPF shows up before a receiver decides for you.",
  diagram_problem=chain("mfrom-p",
    "Diagram of the problem. SPF passes against the SES-owned envelope domain, but that domain is not your From domain, so SPF does not align. DKIM alignment is doing all the work on its own, and the day DKIM has a problem DMARC fails outright.",
    "SPF passes and still does not count, because it passed for the wrong domain.",
    [("Send", "no custom MAIL FROM"),
     ("Envelope domain", "owned by SES"),
     ("SPF", "passes, does not align"),
     ("DMARC", "resting on DKIM alone")],
    fail_at=2),
  diagram_fix=branch("mfrom-f",
    "Diagram of the fix. The MAIL FROM configuration is sorted into aligned and healthy, configured but with the supporting DNS missing, or not configured at all so alignment rests entirely on DKIM.",
    "Two aligned mechanisms is the point. One is a single point of failure you cannot see.",
    ("Read MAIL FROM attributes", "and resolve the supporting DNS"),
    [("Custom domain, MX and SPF present", "SPF aligns, DMARC has two legs", "good"),
     ("Configured, DNS missing", "SES falls back to its own domain", "bad"),
     ("Not configured", "alignment rests on DKIM alone", "bad")]),
),

"email/ses-suppression-list-blocks-a-real-customer": dict(
  flow_intro="A suppressed recipient is dropped after the API call succeeds, so nothing upstream can tell. The script checks the account-level suppression list for the addresses you care about and reports why each one was added and when, which is what decides whether removing it is reasonable.",
  diagram_problem=chain("supp-p",
    "Diagram of the problem. A customer who had one bounce months ago is on the account suppression list. Your application calls SendEmail, SES returns a message ID, and the message is discarded before delivery. Every log upstream records a successful send.",
    "A message ID came back. Nothing in your logs distinguishes this from a delivered email.",
    [("Send to customer", "SendEmail called"),
     ("SES", "returns a message ID"),
     ("Suppression list", "message discarded"),
     ("Your logs", "recorded as sent")],
    fail_at=2),
  diagram_fix=branch("supp-f",
    "Diagram of the fix. Each address is looked up on the suppression list and sorted by why it was added, because a complaint and a stale transient bounce deserve very different treatment.",
    "A complaint is a decision the recipient made. A years-old bounce is usually just stale.",
    ("Query the suppression list", "reason and date per address"),
    [("Not suppressed", "delivery problem is elsewhere", "good"),
     ("Bounce, recent", "the address is genuinely failing", "plain"),
     ("Bounce, long ago", "likely stale, safe to remove", "bad"),
     ("Complaint", "they asked. Do not remove it", "bad")]),
),

"email/ses-bounce-rate-approaching-review": dict(
  flow_intro="The reputation metrics move slowly and the consequence arrives all at once, so the script watches the trend rather than the instant. It reads the bounce and complaint rates against the thresholds that trigger review, and reports how much headroom is left.",
  diagram_problem=chain("bnc-p",
    "Diagram of the problem. A list import adds stale addresses, the bounce rate climbs gradually over days, nothing changes about how sending behaves, and then the account is placed under review with no warning that a threshold was being approached.",
    "The metric moves slowly. The consequence does not.",
    [("Stale list imported", "bounces climb"),
     ("Sending", "behaves exactly as before"),
     ("Threshold crossed", "no warning"),
     ("Account", "under review")],
    fail_at=2),
  diagram_fix=branch("bnc-f",
    "Diagram of the fix. Current bounce and complaint rates are read and sorted by how much headroom remains against the review thresholds, so a rising rate is visible while there is still time to act.",
    "The number to watch is the headroom, not the rate.",
    ("Read reputation metrics", "bounce and complaint rate"),
    [("Well under the threshold", "healthy, keep sending", "good"),
     ("Rising, headroom shrinking", "act now, not at the threshold", "plain"),
     ("At the review threshold", "pause and clean the list", "bad")]),
),

"email/ses-no-event-destination": dict(
  flow_intro="Without an event destination the bounce and complaint events are generated and then dropped, so the data simply does not exist to query later. The script checks each configuration set for a destination and for the event types actually enabled on it.",
  diagram_problem=chain("evt-p",
    "Diagram of the problem. SES emits a bounce event, the configuration set has no event destination attached, the event is discarded, and there is nothing to query afterwards because the data was never stored anywhere.",
    "Not a reporting gap you can backfill. The events were never written down.",
    [("Bounce happens", "SES emits an event"),
     ("Configuration set", "no destination attached"),
     ("Event", "discarded"),
     ("Later", "nothing to query")],
    fail_at=1),
  diagram_fix=branch("evt-f",
    "Diagram of the fix. Each configuration set is sorted by whether a destination exists and whether the event types that matter are actually enabled on it, because a destination subscribed only to sends records nothing useful.",
    "A destination subscribed only to Send events is the same as no destination at all.",
    ("Read each configuration set", "destinations and enabled event types"),
    [("Destination, bounce and complaint on", "events are being recorded", "good"),
     ("Destination, wrong event types", "recording nothing you need", "bad"),
     ("No destination", "events discarded as they happen", "bad")]),
),

"email/list-unsubscribe-missing": dict(
  flow_intro="Since Gmail and Yahoo moved enforcement from deferrals to permanent rejections, a missing one-click header is a hard failure rather than a warning. The script inspects the headers your mail actually carries and checks that the POST endpoint behaves the way RFC 8058 requires.",
  diagram_problem=chain("unsub-p",
    "Diagram of the problem. Bulk mail goes out without a List-Unsubscribe-Post header, the receiving provider rejects it with a permanent 5xx rather than a temporary deferral, and because the failure is permanent nothing retries and the send is simply gone.",
    "It used to be a deferral you could fix later. It is now a permanent rejection.",
    [("Bulk send", "no one-click header"),
     ("Provider check", "requirement not met"),
     ("Permanent 5xx", "not a deferral"),
     ("No retry", "the send is gone")],
    fail_at=1),
  diagram_fix=branch("unsub-f",
    "Diagram of the fix. Outgoing mail is sorted by which unsubscribe headers it carries and whether the endpoint honours a POST without further interaction, since a header pointing at a page that asks the recipient to log in does not satisfy the requirement.",
    "The header is not enough on its own. The endpoint has to work without asking anything of the recipient.",
    ("Inspect the sent headers", "and probe the endpoint"),
    [("Both headers, POST honoured", "compliant", "good"),
     ("Header present, endpoint needs a login", "does not satisfy one-click", "bad"),
     ("mailto: only", "no longer sufficient for bulk", "bad"),
     ("No unsubscribe header", "permanent rejection at the gateway", "bad")]),
),

"email/provider-records-added-to-the-root-domain": dict(
  flow_intro="Two providers each publishing a correct SPF record at the root produces one broken record, because only one is permitted. The script resolves what is actually published and reports the merge that has to happen, rather than which provider to blame.",
  diagram_problem=chain("root-p",
    "Diagram of the problem. A second email provider is onboarded and adds its own SPF record at the root domain. Two SPF records now exist where the specification permits exactly one, so receivers treat the result as a permanent error and both providers lose alignment at once.",
    "Each record is valid. Two of them at the same name is not, and both providers suffer.",
    [("Provider A", "SPF record at the root"),
     ("Provider B", "adds its own"),
     ("Two SPF records", "only one is allowed"),
     ("Receivers", "PermError, both fail")],
    fail_at=2),
  diagram_fix=branch("root-f",
    "Diagram of the fix. The published records are resolved and sorted into a correct single record, several records that must be merged into one, or a single record whose DNS lookup count has grown past the limit that also causes a permanent error.",
    "Merging is the fix for two records. Watch the lookup count while you do it.",
    ("Resolve the root domain", "count records and lookups"),
    [("One SPF record, under the limit", "correct", "good"),
     ("Several SPF records", "merge into one, keep every include", "bad"),
     ("One record, over ten lookups", "PermError for a different reason", "bad")]),
),

}
