#!/usr/bin/env python3
"""Diagrams for /cloudflare/ and /seo/.

Every problem diagram is a chain: these failures are sequences where one step does
something reasonable and the next step does something reasonable and the pair is
wrong. Every fix diagram is a branch, because every script here classifies rather
than guesses -- that is the whole argument of the sections.

No em dashes inside SVG text. An <svg> inherits the document encoding, and a
mis-sniffed page turns one into three mojibake characters inside an image that no
spellcheck will ever look at.
"""
from diagrams import branch, chain

V = {

"cloudflare/too-many-redirects-flexible-ssl": dict(
  flow_intro="We do not guess. The script reads the zone's SSL mode, the Always Use HTTPS setting and whether the origin redirects, then names the combination it found. Only the pairing is a loop, so all three have to be read together before anything is changed.",
  diagram_problem=chain("cfssl-p",
    "Diagram of the problem. The visitor reaches Cloudflare over HTTPS, Cloudflare forwards the request to the origin as plain HTTP because the zone is set to Flexible, the origin answers with a redirect to HTTPS, and that redirect comes back through Cloudflare which sends the same plain HTTP request again.",
    "Both ends behave correctly. It is the pairing that never terminates.",
    [("Visitor", "HTTPS to Cloudflare"),
     ("Cloudflare", "plain HTTP to origin (Flexible)"),
     ("Origin", "301 to HTTPS")],
    fail_at=1, loop=(2, 1, "same request, again")),
  diagram_fix=branch("cfssl-f",
    "Diagram of the fix. A script reads the SSL mode, the Always Use HTTPS setting and the origin's redirect behaviour together, and sorts the zone into one of four states: correct, unvalidated, insecure, or the redirect loop itself.",
    "Reading one setting is not enough. Only the combination tells you which of these four you have.",
    ("Read the zone", "SSL mode, Always Use HTTPS, origin"),
    [("Full (strict)", "origin certificate validated, nothing to do", "good"),
     ("Full", "encrypted but unvalidated, replace the certificate", "plain"),
     ("Flexible, origin does not redirect", "works, but the origin hop is plaintext", "plain"),
     ("Flexible, origin forces HTTPS", "this is the loop. Set Full (strict)", "bad")]),
),

"cloudflare/rule-not-applying-record-not-proxied": dict(
  flow_intro="The rule is not the thing to debug. The script lists every DNS record, works out which ones serve HTTP without being proxied, and cross-references those against the hostnames your rules target, so it can say which specific rule is dead rather than handing you a list of grey clouds to interpret.",
  diagram_problem=chain("cfprox-p",
    "Diagram of the problem. A request for a grey-clouded hostname resolves straight to the origin IP, so it never reaches Cloudflare, and the rule that was written for that hostname is never consulted at all.",
    "Nothing is broken. Cloudflare is simply not in the path, so the rule is never asked.",
    [("Request", "app.example.com"),
     ("DNS answer", "origin IP, DNS only"),
     ("Origin", "serves it directly"),
     ("Your rule", "never consulted")],
    fail_at=2),
  diagram_fix=branch("cfprox-f",
    "Diagram of the fix. The audit sorts every DNS record into records that are correctly proxied, records that must stay unproxied such as MX and TXT, and HTTP records that are unproxied and therefore make any rule targeting them dead.",
    "MX and TXT records are supposed to be grey. Reporting those is how an audit becomes noise nobody reads.",
    ("List every DNS record", "then check the rule targets"),
    [("A or CNAME, proxied", "traffic reaches Cloudflare, rules run", "good"),
     ("MX, TXT, SRV, unproxied", "correct, and never reported", "plain"),
     ("A or CNAME, DNS only", "rule is dead, and the origin IP is public", "bad")]),
),

"cloudflare/only-one-page-rule-applies": dict(
  flow_intro="Page Rules cannot be made to stack, so the fix is either ordering or a different rule engine. The script sorts the rules by priority, walks them for each URL you give it, and reports both the rule that wins and every rule that matched and was thrown away.",
  diagram_problem=chain("cfpr-p",
    "Diagram of the problem. A request matches two Page Rules. Only the higher-priority rule is applied, and the more specific rule below it is discarded with no log line and nothing in the dashboard to show it was skipped.",
    "A broad pattern above a specific one shadows it permanently, and nothing anywhere says so.",
    [("Request", "/promo?utm_source=x"),
     ("example.com/*", "highest priority, wins"),
     ("example.com/promo*", "matches, then discarded")],
    fail_at=1),
  diagram_fix=branch("cfpr-f",
    "Diagram of the fix. For each URL the script reports the winning rule, every rule that matched but was skipped, disabled rules that still consume the plan quota, and the case where the behaviour needs two actions at once and therefore needs the modern rule types instead.",
    "The useful output is the second line: the rules you believe are running and are not.",
    ("Sort by priority", "then walk each URL"),
    [("First match", "the only rule that runs", "good"),
     ("Matched below it", "silently skipped, reorder or merge", "bad"),
     ("Disabled", "does nothing, still eats your quota", "plain"),
     ("Needs two actions", "Page Rules cannot; use Cache and Redirect Rules", "plain")]),
),

"cloudflare/purge-by-url-silently-does-nothing": dict(
  flow_intro="Because the purge response cannot tell you anything, the script goes and looks. It purges, re-requests the URL, and reads CF-Cache-Status, which is the only honest signal available. It also inspects the Cache Rules first, so it can say up front when single-file purge cannot possibly work.",
  diagram_problem=chain("cfpg-p",
    "Diagram of the problem. The purge request names a cache key that does not exist, because the stored object was indexed with a header as part of its key. Removing something that is not there succeeds, so the API returns success and the stale object stays in the cache.",
    "Purge is idempotent. Clearing nothing and clearing the wrong key look identical.",
    [("Purge by URL", "no headers sent"),
     ("Cache key lookup", "key includes a header"),
     ("No match", "nothing removed"),
     ("API says success", "stale object still served")],
    fail_at=1),
  diagram_fix=branch("cfpg-f",
    "Diagram of the fix. After purging, the script re-requests the URL and classifies the CF-Cache-Status header into took effect, revalidating under tiered cache, still cached because the key did not match, or not cached at all.",
    "EXPIRED is not a failure. Under tiered cache it is what a successful purge looks like.",
    ("Purge, then re-request", "read CF-Cache-Status"),
    [("MISS", "the purge took effect", "good"),
     ("EXPIRED", "tiered cache revalidating, also fine", "good"),
     ("HIT, large Age", "key did not match. Purge by prefix or tag", "bad"),
     ("DYNAMIC or BYPASS", "not cached at all, nothing to purge", "plain")]),
),

"seo/sitemap-lists-urls-that-must-not-be-indexed": dict(
  flow_intro="The sitemap is a file you own, so this is a repair rather than a report. The script fetches every URL it lists, checks the four things that disqualify a URL from being recommended, and writes a new sitemap without them, leaving the original in place until you have compared the two.",
  diagram_problem=chain("smap-p",
    "Diagram of the problem. The sitemap generator walks the route list and emits a URL. The page template independently adds a noindex. Nothing joins the two sources, so the sitemap recommends a page that tells the crawler to ignore it.",
    "Two systems, both correct on their own, describing the same page differently.",
    [("Route list", "sitemap generator reads it"),
     ("Sitemap", "recommends the URL"),
     ("Page template", "adds noindex"),
     ("Search Console", "reports the contradiction")],
    fail_at=2),
  diagram_fix=branch("smap-f",
    "Diagram of the fix. Each URL in the sitemap is fetched and sorted into keep, or one of the disqualifying outcomes: it returns an error, it redirects elsewhere, it carries a noindex, or its canonical nominates a different URL.",
    "Anything that is not a plain 200 with a self-referencing canonical comes out of the file.",
    ("Fetch every URL", "status, robots, canonical, host"),
    [("200, self-canonical", "keep it in the sitemap", "good"),
     ("404 or 410", "remove; you are recommending a dead page", "bad"),
     ("301 or 302", "remove, and list the destination instead", "bad"),
     ("noindex, or foreign canonical", "remove; the page disagrees with you", "bad")]),
),

"seo/robots-txt-blocks-the-noindex-you-added": dict(
  flow_intro="Because the two rules cancel, the fix is to stop stacking them. The script implements Google's real matching rule, longest match wins and Allow breaks a tie, tests each URL against the live file, and reports the pages that are both blocked and carrying a noindex, which is the combination that can never resolve.",
  diagram_problem=chain("rob-p",
    "Diagram of the problem. Google reads robots.txt, finds the path disallowed, and never fetches the page. Because it never fetches the page it never sees the noindex, and the URL can remain indexed from inbound links with no description to show.",
    "Belt and braces removed the belt. The crawler never got far enough to read the noindex.",
    [("robots.txt", "Disallow: /private/"),
     ("Crawler", "does not fetch the page"),
     ("noindex", "never read"),
     ("Result", "indexed, no snippet")],
    fail_at=1),
  diagram_fix=branch("rob-f",
    "Diagram of the fix. Each URL is evaluated against the robots rules the way Google evaluates them, and sorted into crawlable, blocked and noindexed which is the conflict, blocked without a noindex, or a blocked CSS or JavaScript file that stops the page rendering.",
    "To remove a page: allow the crawl, serve noindex, wait for the recrawl. Then block it again if you still want to.",
    ("Evaluate each URL", "longest match wins, Allow breaks ties"),
    [("Crawlable", "noindex will be read and obeyed", "good"),
     ("Blocked and noindex", "the conflict. Unblock it first", "bad"),
     ("Blocked, no noindex", "may still be indexed without a snippet", "plain"),
     ("Blocked CSS or JS", "Google cannot render the page as built", "bad")]),
),

"seo/canonical-points-at-staging-or-a-redirect": dict(
  flow_intro="Canonicals come from one base URL, so the repair is a narrow origin swap across the built files rather than a page-by-page edit. The script counts the canonicals on each page first, because zero and two mean different things, then resolves what each one points at.",
  diagram_problem=chain("canon-p",
    "Diagram of the problem. The build substitutes a base URL that was never set in the deploy environment, so every page emits a canonical pointing at localhost or a staging host. The pages look completely normal in a browser because a canonical tag is invisible.",
    "One wrong variable, every page affected identically, and nothing to see on the page.",
    [("Build", "base URL unset, default used"),
     ("Every page", "canonical to staging"),
     ("Google", "follows the nomination"),
     ("Your page", "not the one indexed")],
    fail_at=0),
  diagram_fix=branch("canon-f",
    "Diagram of the fix. Each built page is sorted by how many canonical tags it carries and where the single one points: correct, none at all, more than one which Google ignores entirely, a foreign origin, or a path segment repeated by a concatenation bug.",
    "Two canonicals is worse than none. Google ignores all of them and decides for itself.",
    ("Read the built HTML", "count them, then resolve the target"),
    [("Exactly one, self-referencing", "correct", "good"),
     ("None", "Google picks a URL for you", "plain"),
     ("More than one", "all of them ignored", "bad"),
     ("Staging origin, or doubled path", "one build variable, fixed everywhere", "bad")]),
),

"seo/soft-404-returns-200": dict(
  flow_intro="A status code cannot be un-sent, so this is fixed at the layer that owns the route, not in the page. The script probes a URL that cannot exist under each section you give it and classifies the response by status, redirect behaviour and how much text came back, because all three can be the symptom.",
  diagram_problem=chain("s404-p",
    "Diagram of the problem. The host rewrites every unmatched path to the application shell and answers 200. JavaScript works out afterwards that the route is unknown and renders a not-found message, long after the status line was committed.",
    "The visitor sees the right words. The crawler sees a working page with thin content.",
    [("Request", "/a-path-that-never-existed"),
     ("Catch-all rewrite", "serves the app shell, 200 OK"),
     ("JavaScript", "decides it is unknown"),
     ("Crawler", "records a real page")],
    fail_at=1),
  diagram_fix=branch("s404-f",
    "Diagram of the fix. The probe classifies each response into a correct 404 or 410, a 200 carrying not-found text, a redirect to the homepage, or a 200 with almost no content, all of which Google may treat as a soft 404.",
    "A real 404 with a short body is correct. Flagging that would report every well-behaved site as broken.",
    ("Probe a URL that cannot exist", "status, final path, visible text"),
    [("404 or 410", "correct, whatever the body length", "good"),
     ("200 with not-found text", "status line and page disagree", "bad"),
     ("Redirect to the homepage", "the same bug wearing a hat", "bad"),
     ("200, almost no text", "thin enough to be read as a soft 404", "plain")]),
),

}
