#!/usr/bin/env python3
"""Diagrams for the /stripe/ field notes, batch S.

Same two shapes as the rest of the site: the problem is a chain that breaks at
one step, the fix is a branch, because every script in this section classifies
what it finds rather than guessing. Drawn in Stripe indigo.

No em dashes inside SVG text. One mis-sniffed encoding turns a single character
into three mojibake ones inside an image, where nothing will catch it.
"""
import diagrams as D

# Set before the diagrams below are built, restored at the bottom of the module.
# Every diagram here is constructed at import time, so the theme has to be active
# across exactly this file and no further.
BRAND = "#635BFF"
D.set_theme(BRAND)

V = {}

V["stripe/non-https-or-tunnel-webhook-url"] = {
    "flow_intro": (
        "The script parses the hostname out of every endpoint URL before judging it, "
        "because the mode decides the verdict: the same tunnel name is a working day "
        "in test mode and an outage in live."
    ),
    "diagram_problem": D.chain(
        "shtu-p",
        "A tunnel hostname left in a live webhook endpoint after the tunnel closed",
        "Nothing reaches your code, so nothing appears in your logs, your error "
        "tracker or your uptime monitor.",
        [
            ("Tunnel started", "for an afternoon"),
            ("URL registered", "in live mode"),
            ("Tunnel closed", "hostname released"),
            ("Delivery fails", "cannot connect"),
            ("Endpoint disabled", "after 3 days"),
        ],
        fail_at=2,
    ),
    "diagram_fix": D.branch(
        "shtu-f",
        "Sorting webhook endpoint URLs by whether Stripe can reach the host",
        "Judged on the parsed hostname, not the string. A suffix match keeps "
        "localhost-tools.example.com out of the findings.",
        ("GET /v1/webhook_endpoints", "url plus livemode"),
        [
            ("Public https host", "reachable, leave it", "good"),
            ("Tunnel host, test mode", "somebody is working", "plain"),
            ("Tunnel host, live mode", "repoint or delete it", "bad"),
            ("localhost or RFC1918", "never reachable at all", "bad"),
            ("Scheme is http", "TLS 1.2 or 1.3 only", "bad"),
        ],
    ),
}

V["stripe/unsubscribed-event-types-firing"] = {
    "flow_intro": (
        "The script unions the subscribed types across every endpoint, then tallies "
        "what actually fired over the retained window, because coverage is a property "
        "of the account and not of any one endpoint."
    ),
    "diagram_problem": D.chain(
        "suet-p",
        "An event type generated by Stripe and delivered to no endpoint at all",
        "No delivery is attempted, so nothing counts as a failure and every webhook "
        "health check keeps reporting green.",
        [
            ("Product enabled", "Radar, Tax, Billing"),
            ("New type fires", "visible in /v1/events"),
            ("Allowlist checked", "type not listed"),
            ("Nothing queued", "no delivery attempt"),
            ("No error anywhere", "found months later"),
        ],
        fail_at=2,
    ),
    "diagram_fix": D.branch(
        "suet-f",
        "Sorting fired event types by whether any endpoint subscribes to them",
        "Only the literal star is a wildcard. A namespace pattern is a string that "
        "never equals a real type.",
        ("Union of enabled_events", "against a tally of /v1/events"),
        [
            ("Type is subscribed", "covered", "good"),
            ("Star subscription", "covered, but flooding", "plain"),
            ("Sibling subscribed only", "a near miss, add the type", "bad"),
            ("Namespace unhandled", "nothing here reaches you", "bad"),
        ],
    ),
}

V["stripe/charge-events-but-paymentintent-integration"] = {
    "flow_intro": (
        "The script reads each endpoint's subscription and then asks which events the "
        "account actually generates, because the same enabled_events list is correct "
        "on a Charges integration and broken on a PaymentIntents one."
    ),
    "diagram_problem": D.chain(
        "sceb-p",
        "Fulfilment running on a Charge that carries none of the intent metadata",
        "The handler returns 200 every time, so the endpoint stays healthy while "
        "nothing can be mapped back to an order.",
        [
            ("Code moves to intents", "metadata on the intent"),
            ("Endpoint unchanged", "not in the diff"),
            ("charge.succeeded fires", "Charge in the payload"),
            ("metadata empty", "no cart, no user"),
            ("Order unmatched", "or fetched again live"),
        ],
        fail_at=3,
    ),
    "diagram_fix": D.branch(
        "sceb-f",
        "Sorting fulfilment subscriptions by the integration era the account is in",
        "The traffic decides. Charge events with no intent traffic behind them are a "
        "legacy integration, not a stale subscription.",
        ("enabled_events per endpoint", "plus the types seen firing"),
        [
            ("Intent or session events", "aligned", "good"),
            ("Charge only, no intents", "a real Charges integration", "plain"),
            ("Charge only, intents fire", "one era behind", "bad"),
            ("Sessions fire, unsubscribed", "Checkout never fulfils", "bad"),
            ("Charge plus intent", "one payment handled twice", "bad"),
        ],
    ),
}

V["stripe/missing-payment-failure-events"] = {
    "flow_intro": (
        "The script checks two surfaces separately, because a missing invoice event "
        "is noise on an account with no subscriptions and a running incident on one "
        "where invoices are already failing."
    ),
    "diagram_problem": D.chain(
        "smpfe-p",
        "A declined renewal running through dunning with the application never told",
        "The failure state looks exactly like silence: the intent drops back and the "
        "invoice goes past due, and neither pushes anything.",
        [
            ("Renewal declines", "card expired"),
            ("Invoice past due", "retries scheduled"),
            ("No subscription", "event never delivered"),
            ("Access unchanged", "still fully provisioned"),
            ("Found by support", "weeks of free service"),
        ],
        fail_at=2,
    ),
    "diagram_fix": D.branch(
        "smpfe-f",
        "Sorting failure event coverage by surface and by failures already seen",
        "The one off path and the billing path are separate subscriptions, and no "
        "success event implies either of them.",
        ("Union of enabled_events", "plus subscriptions and failures"),
        [
            ("Both failures subscribed", "covered", "good"),
            ("No payment events at all", "the endpoint is the gap", "plain"),
            ("Success without failure", "declines go nowhere", "bad"),
            ("Billing gap, none failed yet", "a gap to close", "bad"),
            ("Billing gap, invoices failed", "an incident running now", "bad"),
        ],
    ),
}

# Back to the default so an import after this one is unaffected.
D.reset_theme()
