#!/usr/bin/env python3
"""Diagrams for /ci/ and /aws/.

The CI problems all share one shape: something degrades gracefully, which is correct
behaviour and exactly what hides it, so the problem chain always ends in a green tick
rather than an error. The AWS ones share a different shape: a resource outlives the
thing that justified it, and the meter keeps running.
"""
from diagrams import branch, chain

V = {

"ci/secrets-are-empty-in-fork-pull-requests": dict(
  flow_intro="The script does not try to make secrets available to forks, because that is the exfiltration path, not the fix. It reads the workflow files and reports where a secret is used in a way that fails open: in a condition, where an empty string is falsy, or in a step whose failure is swallowed downstream.",
  diagram_problem=chain("cisec-p",
    "Diagram of the problem. A pull request from a fork triggers the workflow, GitHub resolves every secret to an empty string rather than raising an error, the deploy step's condition evaluates that empty string as false, the step is skipped, and the job reports success having done nothing.",
    "Nothing errors. The job goes green having skipped the only step that mattered.",
    [("Fork pull request", "workflow triggers"),
     ("Secrets", "resolve to empty strings"),
     ("if: secrets.TOKEN", "empty is falsy, step skipped"),
     ("Job", "green, nothing deployed")],
    fail_at=1),
  diagram_fix=branch("cisec-f",
    "Diagram of the fix. Each use of a secret in a workflow is sorted into safe on a fork, a silent skip caused by using the secret in a condition, a misleading 401 downstream, or the pull_request_target trigger which hands an untrusted branch your credentials.",
    "The dangerous one is the last: pull_request_target looks like the fix and is an exfiltration path.",
    ("Read the workflow files", "find every secrets.* reference"),
    [("Guarded by event name", "explicitly skipped, and says so", "good"),
     ("Used in an if:", "silently skips, job still green", "bad"),
     ("Passed to an API call", "401 that reads as a service outage", "bad"),
     ("pull_request_target", "untrusted code, your secrets", "bad")]),
),

"ci/github-token-is-read-only-by-default": dict(
  flow_intro="The 403 does not name the missing scope, so the script maps it back. It reads what each job actually does, works out which permission that needs, and compares it against the permissions block, flagging the trap that a block replaces the defaults rather than adding to them.",
  diagram_problem=chain("citok-p",
    "Diagram of the problem. A workflow step tries to push a package, the default GITHUB_TOKEN has read-only contents access, and the API returns a 403 whose message is identical whether the missing scope is contents, packages, issues or id-token.",
    "The same message for every missing scope, on purpose: naming it would tell an attacker what to aim for.",
    [("Step runs", "publishes a package"),
     ("GITHUB_TOKEN", "read-only by default"),
     ("API", "403, scope not named"),
     ("You", "guess which one")],
    fail_at=1),
  diagram_fix=branch("citok-f",
    "Diagram of the fix. Each job is sorted by whether its permissions are sufficient, missing entirely, narrower than the work it does, or written as a block that silently replaced the defaults so fixing one 403 produced another.",
    "A permissions block replaces the defaults. That is why fixing one 403 so often produces the next one.",
    ("Read each job", "what it does, what it is granted"),
    [("Permissions match the work", "nothing to change", "good"),
     ("No permissions block", "read-only default, writes will 403", "plain"),
     ("Block present, scope missing", "add just that scope, not write-all", "bad"),
     ("Block replaced the defaults", "fixing one 403 produced another", "bad")]),
),

"ci/cache-miss-is-really-a-rate-limit": dict(
  flow_intro="A cache miss and a throttled cache request produce the same log line, so the script asks the API instead of reading logs. It compares cache hit rates across recent runs and flags the pattern that means throttling rather than a genuinely cold cache.",
  diagram_problem=chain("cicache-p",
    "Diagram of the problem. The cache service rate-limits the request, the action reports a cache miss because a missing cache must never break a build, the job restores nothing and rebuilds from scratch, and the only visible symptom is that runs got slower.",
    "Degrading to a miss is correct behaviour. It is also indistinguishable from a cold cache.",
    [("Restore cache", "request sent"),
     ("Rate limit", "reported as a miss"),
     ("Job", "rebuilds from scratch"),
     ("Log", "cache not found")],
    fail_at=1),
  diagram_fix=branch("cicache-f",
    "Diagram of the fix. Cache behaviour across recent runs is sorted into healthy hits, a genuine first-run miss, a key that changed so nothing could ever match, and a miss rate high enough across concurrent jobs to mean throttling.",
    "One miss is a cold cache. A miss on every concurrent job at once is a rate limit.",
    ("Compare recent runs", "hit rate, keys, concurrency"),
    [("Steady hit rate", "the cache is working", "good"),
     ("First run for a key", "expected miss, ignore it", "plain"),
     ("Key changed every run", "nothing can ever match it", "bad"),
     ("Misses cluster on parallel jobs", "throttling, not a cold cache", "bad")]),
),

"ci/redundant-runs-on-rapid-pushes": dict(
  flow_intro="Whether a run is safe to cancel is a judgement about your deploys, so the script reports rather than edits. It finds the workflows where superseded runs are still billing minutes and shows what a concurrency group would have saved, leaving the decision with you.",
  diagram_problem=chain("cirun-p",
    "Diagram of the problem. Three pushes land in quick succession, each starts a full workflow run, and the first two keep running to completion against commits nobody will ever ship, billing minutes the whole time.",
    "Every run finishes. Only the last one was ever going to matter.",
    [("Push, push, push", "three commits, minutes apart"),
     ("Three runs start", "no concurrency group"),
     ("Two run to completion", "against dead commits"),
     ("Bill", "triple, for one result")],
    fail_at=1),
  diagram_fix=branch("cirun-f",
    "Diagram of the fix. Workflows are sorted into those already using a concurrency group, those where superseded runs are billing minutes, those on expensive macOS runners where the waste is ten times worse, and deploy workflows where cancelling mid-run is not safe.",
    "macOS runners bill at ten times the rate, so the same waste costs ten times as much there.",
    ("Read recent runs", "per workflow, per runner type"),
    [("Concurrency group set", "superseded runs cancel themselves", "good"),
     ("Superseded runs complete", "minutes spent on dead commits", "bad"),
     ("On a macOS runner", "same waste, ten times the price", "bad"),
     ("Deploy workflow", "do not auto-cancel; your call", "plain")]),
),

"aws/nat-gateway-idle-with-no-traffic": dict(
  flow_intro="A NAT gateway bills for existing, not for working, so the question is whether anything still routes through it. The script reads the CloudWatch bytes-processed metric over a window you choose and separates gateways doing real work from ones that have been idle since whatever needed them was torn down.",
  diagram_problem=chain("nat-p",
    "Diagram of the problem. A private subnet needed outbound access, a NAT gateway was created for it, the workload was later deleted, and the gateway stayed behind billing an hourly rate whether or not a single byte passes through it.",
    "Roughly thirty-two dollars a month, per gateway, for a route nothing uses any more.",
    [("Workload needed egress", "NAT gateway created"),
     ("Workload deleted", "gateway left behind"),
     ("Zero bytes processed", "still provisioned"),
     ("Hourly charge", "continues regardless")],
    fail_at=1),
  diagram_fix=branch("nat-f",
    "Diagram of the fix. Each NAT gateway is sorted by the bytes it processed over the lookback window: actively used, quiet but still referenced by a route table, or idle with nothing routing to it at all.",
    "Idle is not the same as unreferenced. Check the route tables before deleting anything.",
    ("Read BytesOutToDestination", "per gateway, over the window"),
    [("Traffic in the window", "in use, leave it alone", "good"),
     ("Idle, route table still points at it", "something may still need it", "plain"),
     ("Idle, nothing routes to it", "billing for a route nothing uses", "bad")]),
),

"aws/unattached-ebs-volumes": dict(
  flow_intro="A detached volume looks like a safety net and bills like storage. The script lists volumes in the available state, reads how long they have been that way and whether a snapshot exists, so deleting one is a decision with the facts in front of you rather than a guess.",
  diagram_problem=chain("ebs-p",
    "Diagram of the problem. An instance is terminated, its data volume was not set to delete on termination, so the volume survives in the available state and keeps billing per provisioned gigabyte per month whether or not anything ever reads from it.",
    "The volume outlived the instance. Provisioned capacity bills the same whether it is read or not.",
    [("Instance terminated", "volume set to persist"),
     ("Volume", "state: available"),
     ("Nothing attached", "nothing reads it"),
     ("Charge", "per provisioned GB, monthly")],
    fail_at=1),
  diagram_fix=branch("ebs-f",
    "Diagram of the fix. Available volumes are sorted by age and by whether a snapshot exists, so a recently detached volume is treated differently from one that has been sitting unattached for months with a snapshot already taken.",
    "Age and a snapshot are what turn this from a guess into a decision.",
    ("List volumes in 'available'", "with age and snapshot state"),
    [("Attached", "in use, not a finding", "good"),
     ("Detached recently", "may be mid-migration, leave it", "plain"),
     ("Detached for months, snapshot exists", "safe to delete, restore path intact", "bad"),
     ("Detached for months, no snapshot", "snapshot first, then delete", "bad")]),
),

"aws/orphaned-ebs-snapshots": dict(
  flow_intro="Snapshots outlive the volumes they were taken from and nothing cleans them up. The script walks every snapshot, resolves whether its source volume still exists and whether an AMI still references it, and separates the ones that are still a restore path from the ones that are only a bill.",
  diagram_problem=chain("snap-p",
    "Diagram of the problem. A backup job takes a snapshot on a schedule, the source volume is later deleted, and the snapshots remain because nothing ties their lifecycle to the volume's. Nobody notices because a snapshot is cheap and there are thousands of them.",
    "Individually trivial, collectively not. Nothing deletes a snapshot when its volume goes.",
    [("Scheduled snapshots", "taken on a timer"),
     ("Source volume deleted", "snapshots unaffected"),
     ("No lifecycle rule", "nothing prunes them"),
     ("Thousands", "small charge, large total")],
    fail_at=1),
  diagram_fix=branch("snap-f",
    "Diagram of the fix. Each snapshot is sorted by whether its source volume still exists and whether an AMI still references it, because deleting a snapshot an AMI depends on quietly breaks that image.",
    "A snapshot backing an AMI is not orphaned. Deleting it breaks the image without an error.",
    ("Walk every snapshot", "resolve volume and AMI references"),
    [("Source volume exists", "an active restore point", "good"),
     ("Referenced by an AMI", "deleting it breaks the image", "plain"),
     ("Volume gone, no AMI, recent", "keep briefly, then prune", "plain"),
     ("Volume gone, no AMI, old", "a bill with no restore path", "bad")]),
),

"aws/public-ipv4-now-always-charged": dict(
  flow_intro="Since February 2024 every public IPv4 address bills hourly, attached or not, which turned a pile of harmless leftovers into a line item. The script counts them all and separates addresses doing a job from ones nothing points at.",
  diagram_problem=chain("ipv4-p",
    "Diagram of the problem. Elastic IPs were allocated for instances that no longer exist. Before February 2024 an attached address was free, so nobody tracked them. Now every public IPv4 address bills hourly whether it is attached to anything or not.",
    "The addresses did not change. The billing rule did, and the leftovers became a line item.",
    [("IPs allocated", "for instances long gone"),
     ("Before Feb 2024", "attached addresses were free"),
     ("Rule changed", "all IPv4 billed hourly"),
     ("Leftovers", "now a monthly charge")],
    fail_at=2),
  diagram_fix=branch("ipv4-f",
    "Diagram of the fix. Every public IPv4 address in the account is sorted into attached and serving traffic, attached to something stopped, or allocated and associated with nothing at all.",
    "Unassociated is the obvious one. Attached to a stopped instance bills exactly the same.",
    ("Count every public IPv4", "Elastic IPs and auto-assigned"),
    [("Attached, instance running", "doing a job", "good"),
     ("Attached, instance stopped", "bills the same as a running one", "bad"),
     ("Allocated, associated with nothing", "pure waste", "bad")]),
),

"aws/cloudwatch-logs-never-expire": dict(
  flow_intro="Log groups are created automatically with retention set to Never expire, so this accumulates without anyone choosing it. The script lists every group with its retention and stored bytes, so you can see which ones are genuinely growing without bound before setting a policy.",
  diagram_problem=chain("cwl-p",
    "Diagram of the problem. A Lambda function is created, its log group is created automatically with no retention policy, and every line it has ever written is still stored and still billed years later.",
    "Nobody chose Never expire. It is what you get when nobody chooses anything.",
    [("Lambda created", "log group auto-created"),
     ("Retention", "defaults to Never expire"),
     ("Years of logs", "all still stored"),
     ("Storage charge", "grows forever")],
    fail_at=1),
  diagram_fix=branch("cwl-f",
    "Diagram of the fix. Log groups are sorted by whether a retention policy is set and how much they store, separating a deliberate compliance retention from a group that simply never had a policy and is now the largest thing in the account.",
    "Some retention is deliberate. The script says which groups are large, not which to delete.",
    ("List every log group", "retention and stored bytes"),
    [("Retention set deliberately", "leave it, it was a decision", "good"),
     ("Never expire, small", "worth setting, not urgent", "plain"),
     ("Never expire, large and growing", "the bill nobody chose", "bad")]),
),

"aws/untagged-resources-break-cost-attribution": dict(
  flow_intro="Cost allocation only works on tags that exist, so an untagged resource is invisible in every per-team report while still costing money. The script measures tag coverage against the keys you actually use and reports what falls through.",
  diagram_problem=chain("tag-p",
    "Diagram of the problem. A resource is created without the cost allocation tags, Cost Explorer groups it under no value for that key, the per-team report shows a gap nobody owns, and the spend is real but unattributable.",
    "The money is spent either way. Only the ability to say whose it was disappears.",
    [("Resource created", "no cost tags applied"),
     ("Cost Explorer", "groups it as no value"),
     ("Team report", "a gap nobody owns"),
     ("Spend", "real, unattributable")],
    fail_at=1),
  diagram_fix=branch("tag-f",
    "Diagram of the fix. Resources are measured against the tag keys you actually report on, and sorted into fully tagged, missing a key, tagged with an inconsistent value such as a case or spelling variant, and completely untagged.",
    "Inconsistent values are worse than missing ones: they split one team's spend across several rows.",
    ("Read every resource", "against the keys you report on"),
    [("All required keys present", "attributable", "good"),
     ("Missing one key", "partially attributable", "plain"),
     ("Value spelled inconsistently", "splits one team across rows", "bad"),
     ("No tags at all", "invisible in every report", "bad")]),
),

}
