"""Facts about the live Excel products. GENERATED — do not hand-edit.

Written by extract_catalog.py from <line>-results.tsv, <line>-manifest.tsv
and the shipped .xlsx files in ~/Projects/gumroad-products. Re-run the
extractor after any price change or republish.
"""

PRODUCTS = [{'key': 'construction-wip-schedule-workbook',
  'line': 'wip',
  'gumroad_title': 'Construction WIP Schedule Template — Excel Percentage of Completion, Fade '
                   '& Bonding',
  'summary': 'Eight-tab construction WIP schedule for Excel & Google Sheets — percentage of '
             'completion with proper loss accrual, roll-forward, gross profit fade, '
             'income-statement tie-out and bonding ratios.',
  'price': 119,
  'url': 'https://thecalmdeskco.gumroad.com/l/construction-wip-schedule-template',
  'product_id': 'aPLRcp1X6ehKuHdqAueQig==',
  'category': 'business-and-money/accounting',
  'tags': ['wip schedule',
           'construction',
           'contractor',
           'percentage complete',
           'surety',
           'bonding',
           'excel template',
           'google sheets',
           'accounting',
           'cfo',
           'controller',
           'digital download'],
  'tabs': ['Start Here',
           'Contracts',
           'WIP Schedule',
           'Roll-Forward',
           'Fade Analysis',
           'Tie-Out',
           'Bonding',
           'How It Works'],
  'functions': ['ABS',
                'AND',
                'COUNTIF',
                'IF',
                'IFERROR',
                'MAX',
                'MIN',
                'ROUND',
                'SUM',
                'SUMIF'],
  'notable_functions': [],
  'xlsx': '/Users/allanninal/Projects/gumroad-products/wip/construction-wip-schedule-workbook/Construction-WIP-Schedule-Percentage-of-Completion.xlsx',
  'cover': '/Users/allanninal/Projects/gumroad-products/wip/construction-wip-schedule-workbook/cover.png',
  'created_at': '2026-08-22T17:23:22Z',
  'gumroad_name': 'Construction WIP Schedule Template — Excel Percentage of Completion, Fade & '
                  'Bonding',
  'sales_count': 0},
 {'key': 'car-wash-underwriting-model',
  'line': 'underwriting',
  'gumroad_title': 'Car Wash Underwriting Model — Excel & Google Sheets Deal Analyzer with '
                   'IRR, DSCR & Sensitivity',
  'summary': 'Eight-tab express tunnel car wash underwriting model for Excel & Google Sheets — '
             '10-year proforma, real amortisation, levered and unlevered IRR, DSCR and a 5x5 '
             'sensitivity grid.',
  'price': 99,
  'url': 'https://thecalmdeskco.gumroad.com/l/car-wash-underwriting-model',
  'product_id': 'DbmYrgFjgUHPSMOR8YmccA==',
  'category': 'business-and-money/investing',
  'tags': ['car wash',
           'underwriting',
           'real estate',
           'deal analyzer',
           'irr calculator',
           'cap rate',
           'excel template',
           'google sheets',
           'proforma',
           'dscr',
           'investing',
           'digital download'],
  'tabs': ['Start Here',
           'Assumptions',
           'Revenue',
           'Operating Expenses',
           'Debt Schedule',
           'Proforma',
           'Returns',
           'Sensitivity'],
  'functions': ['CUMIPMT',
                'CUMPRINC',
                'IF',
                'IFERROR',
                'INDEX',
                'IRR',
                'PMT',
                'ROUND',
                'SUM',
                'SUMPRODUCT'],
  'notable_functions': ['CUMIPMT', 'CUMPRINC', 'IRR', 'PMT'],
  'xlsx': '/Users/allanninal/Projects/gumroad-products/underwriting/car-wash-underwriting-model/Car-Wash-Underwriting-Model.xlsx',
  'cover': '/Users/allanninal/Projects/gumroad-products/underwriting/car-wash-underwriting-model/cover.png',
  'created_at': '2026-08-21T15:27:50Z',
  'gumroad_name': 'Car Wash Underwriting Model — Excel & Google Sheets Deal Analyzer with IRR, '
                  'DSCR & Sensitivity',
  'sales_count': 0},
 {'key': 'construction-cash-flow-forecast',
  'line': 'cashflow',
  'gumroad_title': 'Construction Cash Flow Forecast — Excel Peak Funding Need, S-Curve & Line '
                   'of Credit',
  'summary': 'Eight-tab construction cash flow forecast for Excel & Google Sheets — S-curve '
             'revenue, collection lags, retainage release, cost payment timing, line of credit '
             'and peak funding need.',
  'price': 99,
  'url': 'https://thecalmdeskco.gumroad.com/l/construction-cash-flow-forecast',
  'product_id': 'Fvc8Y1ad7kT1jXSzDAusyg==',
  'category': 'business-and-money/accounting',
  'tags': ['cash flow forecast',
           'construction',
           'contractor',
           'peak funding',
           's-curve',
           'line of credit',
           'excel template',
           'google sheets',
           'cfo',
           'working capital',
           'retainage',
           'digital download'],
  'tabs': ['Start Here',
           'Assumptions',
           'Jobs',
           'Revenue & Billing',
           'Costs & Payments',
           'Cash Flow',
           'Stress Test',
           'How It Works'],
  'functions': ['AND',
                'COUNTIF',
                'IF',
                'IFERROR',
                'ISNUMBER',
                'MATCH',
                'MAX',
                'MIN',
                'SUM',
                'SUMPRODUCT'],
  'notable_functions': [],
  'xlsx': '/Users/allanninal/Projects/gumroad-products/cashflow/construction-cash-flow-forecast/Construction-Cash-Flow-Forecast-Workbook.xlsx',
  'cover': '/Users/allanninal/Projects/gumroad-products/cashflow/construction-cash-flow-forecast/cover.png',
  'created_at': '2026-08-22T18:53:40Z',
  'gumroad_name': 'Construction Cash Flow Forecast — Excel Peak Funding Need, S-Curve & Line '
                  'of Credit',
  'sales_count': 0},
 {'key': 'laundromat-underwriting-model',
  'line': 'underwriting',
  'gumroad_title': 'Laundromat Underwriting Model — Excel & Google Sheets Deal Analyzer with '
                   'IRR, DSCR & Sensitivity',
  'summary': 'Eight-tab laundromat underwriting model for Excel & Google Sheets — 10-year '
             'proforma, real amortisation, levered and unlevered IRR, DSCR and a 5x5 '
             'sensitivity grid.',
  'price': 99,
  'url': 'https://thecalmdeskco.gumroad.com/l/laundromat-underwriting-model',
  'product_id': 'G8sDjJgt5ajO12MzGAKSdA==',
  'category': 'business-and-money/investing',
  'tags': ['laundromat',
           'underwriting',
           'real estate',
           'deal analyzer',
           'irr calculator',
           'cap rate',
           'excel template',
           'google sheets',
           'proforma',
           'dscr',
           'investing',
           'digital download'],
  'tabs': ['Start Here',
           'Assumptions',
           'Revenue',
           'Operating Expenses',
           'Debt Schedule',
           'Proforma',
           'Returns',
           'Sensitivity'],
  'functions': ['CUMIPMT',
                'CUMPRINC',
                'IF',
                'IFERROR',
                'INDEX',
                'IRR',
                'PMT',
                'ROUND',
                'SUM',
                'SUMPRODUCT'],
  'notable_functions': ['CUMIPMT', 'CUMPRINC', 'IRR', 'PMT'],
  'xlsx': '/Users/allanninal/Projects/gumroad-products/underwriting/laundromat-underwriting-model/Laundromat-Underwriting-Model.xlsx',
  'cover': '/Users/allanninal/Projects/gumroad-products/underwriting/laundromat-underwriting-model/cover.png',
  'created_at': '2026-08-21T15:28:14Z',
  'gumroad_name': 'Laundromat Underwriting Model — Excel & Google Sheets Deal Analyzer with '
                  'IRR, DSCR & Sensitivity',
  'sales_count': 0},
 {'key': 'mobile-home-park-underwriting-model',
  'line': 'underwriting',
  'gumroad_title': 'Mobile Home Park Underwriting Model — Excel & Google Sheets Deal Analyzer '
                   'with IRR, DSCR & Sensitivity',
  'summary': 'Eight-tab mobile home park underwriting model for Excel & Google Sheets — '
             '10-year proforma, real amortisation, levered and unlevered IRR, DSCR and a 5x5 '
             'sensitivity grid.',
  'price': 99,
  'url': 'https://thecalmdeskco.gumroad.com/l/mobile-home-park-underwriting-model',
  'product_id': 'j-hOXjedjt2VhZIjTSbIqA==',
  'category': 'business-and-money/investing',
  'tags': ['mobile home park',
           'underwriting',
           'real estate',
           'deal analyzer',
           'irr calculator',
           'cap rate',
           'excel template',
           'google sheets',
           'proforma',
           'dscr',
           'investing',
           'digital download'],
  'tabs': ['Start Here',
           'Assumptions',
           'Revenue',
           'Operating Expenses',
           'Debt Schedule',
           'Proforma',
           'Returns',
           'Sensitivity'],
  'functions': ['CUMIPMT',
                'CUMPRINC',
                'IF',
                'IFERROR',
                'INDEX',
                'IRR',
                'PMT',
                'ROUND',
                'SUM',
                'SUMPRODUCT'],
  'notable_functions': ['CUMIPMT', 'CUMPRINC', 'IRR', 'PMT'],
  'xlsx': '/Users/allanninal/Projects/gumroad-products/underwriting/mobile-home-park-underwriting-model/Mobile-Home-Park-Underwriting-Model.xlsx',
  'cover': '/Users/allanninal/Projects/gumroad-products/underwriting/mobile-home-park-underwriting-model/cover.png',
  'created_at': '2026-08-21T15:28:06Z',
  'gumroad_name': 'Mobile Home Park Underwriting Model — Excel & Google Sheets Deal Analyzer '
                  'with IRR, DSCR & Sensitivity',
  'sales_count': 0},
 {'key': 'rv-park-underwriting-model',
  'line': 'underwriting',
  'gumroad_title': 'RV Park Underwriting Model — Excel & Google Sheets Deal Analyzer with IRR, '
                   'DSCR & Sensitivity',
  'summary': 'Eight-tab RV park & campground underwriting model for Excel & Google Sheets — '
             '10-year proforma, real amortisation, levered and unlevered IRR, DSCR and a 5x5 '
             'sensitivity grid.',
  'price': 99,
  'url': 'https://thecalmdeskco.gumroad.com/l/rv-park-underwriting-model',
  'product_id': 'rCnRGKsLX6rdqMv1sLrewA==',
  'category': 'business-and-money/investing',
  'tags': ['rv park',
           'underwriting',
           'real estate',
           'deal analyzer',
           'irr calculator',
           'cap rate',
           'excel template',
           'google sheets',
           'proforma',
           'dscr',
           'investing',
           'digital download'],
  'tabs': ['Start Here',
           'Assumptions',
           'Revenue',
           'Operating Expenses',
           'Debt Schedule',
           'Proforma',
           'Returns',
           'Sensitivity'],
  'functions': ['CUMIPMT',
                'CUMPRINC',
                'IF',
                'IFERROR',
                'INDEX',
                'IRR',
                'PMT',
                'ROUND',
                'SUM',
                'SUMPRODUCT'],
  'notable_functions': ['CUMIPMT', 'CUMPRINC', 'IRR', 'PMT'],
  'xlsx': '/Users/allanninal/Projects/gumroad-products/underwriting/rv-park-underwriting-model/RV-Park-Underwriting-Model.xlsx',
  'cover': '/Users/allanninal/Projects/gumroad-products/underwriting/rv-park-underwriting-model/cover.png',
  'created_at': '2026-08-21T15:27:58Z',
  'gumroad_name': 'RV Park Underwriting Model — Excel & Google Sheets Deal Analyzer with IRR, '
                  'DSCR & Sensitivity',
  'sales_count': 0},
 {'key': 'self-storage-underwriting-model',
  'line': 'underwriting',
  'gumroad_title': 'Self-Storage Underwriting Model — Excel & Google Sheets Deal Analyzer with '
                   'IRR, DSCR & Sensitivity',
  'summary': 'Eight-tab self-storage facility underwriting model for Excel & Google Sheets — '
             '10-year proforma, real amortisation, levered and unlevered IRR, DSCR and a 5x5 '
             'sensitivity grid.',
  'price': 99,
  'url': 'https://thecalmdeskco.gumroad.com/l/self-storage-underwriting-model',
  'product_id': 'FS86a9zUTNOlWbyP06p53g==',
  'category': 'business-and-money/investing',
  'tags': ['self storage',
           'underwriting',
           'real estate',
           'deal analyzer',
           'irr calculator',
           'cap rate',
           'excel template',
           'google sheets',
           'proforma',
           'dscr',
           'investing',
           'digital download'],
  'tabs': ['Start Here',
           'Assumptions',
           'Revenue',
           'Operating Expenses',
           'Debt Schedule',
           'Proforma',
           'Returns',
           'Sensitivity'],
  'functions': ['CUMIPMT',
                'CUMPRINC',
                'IF',
                'IFERROR',
                'INDEX',
                'IRR',
                'PMT',
                'ROUND',
                'SUM',
                'SUMPRODUCT'],
  'notable_functions': ['CUMIPMT', 'CUMPRINC', 'IRR', 'PMT'],
  'xlsx': '/Users/allanninal/Projects/gumroad-products/underwriting/self-storage-underwriting-model/Self-Storage-Underwriting-Model.xlsx',
  'cover': '/Users/allanninal/Projects/gumroad-products/underwriting/self-storage-underwriting-model/cover.png',
  'created_at': '2026-08-21T15:27:37Z',
  'gumroad_name': 'Self-Storage Underwriting Model — Excel & Google Sheets Deal Analyzer with '
                  'IRR, DSCR & Sensitivity',
  'sales_count': 0},
 {'key': 'certified-payroll-davis-bacon',
  'line': 'payroll',
  'gumroad_title': 'Certified Payroll & Davis-Bacon Fringe Calculator — WH-347, Annualization, '
                   'Excel + Sheets',
  'summary': 'Annualizes fringe benefit credits on TOTAL annual hours — not Davis-Bacon hours '
             '— and lays the week out in WH-347 order. Excel + Google Sheets.',
  'price': 89,
  'url': 'https://thecalmdeskco.gumroad.com/l/certified-payroll-davis-bacon-fringe-calculator',
  'product_id': 'W7lmBlWt6-_4sbhf8X9csA==',
  'category': 'business-and-money/accounting',
  'tags': ['certified payroll',
           'davis bacon',
           'prevailing wage',
           'wh-347',
           'contractor payroll',
           'fringe benefits',
           'payroll excel',
           'compliance'],
  'tabs': ['Start Here',
           'Wage Determination',
           'Employees',
           'Annualization',
           'Weekly Payroll',
           'WH-347 Output',
           'Checks',
           'How It Works'],
  'functions': ['ABS',
                'COUNTIF',
                'IF',
                'IFERROR',
                'ISNUMBER',
                'MAX',
                'MIN',
                'ROUND',
                'SUM',
                'SUMIF',
                'SUMPRODUCT',
                'VLOOKUP'],
  'notable_functions': [],
  'xlsx': '/Users/allanninal/Projects/gumroad-products/payroll/certified-payroll-davis-bacon/Certified-Payroll-Davis-Bacon-Fringe-Workbook.xlsx',
  'cover': '/Users/allanninal/Projects/gumroad-products/payroll/certified-payroll-davis-bacon/cover.png',
  'created_at': '2026-08-23T11:42:48Z',
  'gumroad_name': 'Certified Payroll & Davis-Bacon Fringe Calculator — WH-347, Annualization, '
                  'Excel + Sheets',
  'sales_count': 0},
 {'key': 'concrete-bid-calculator',
  'line': 'trades',
  'gumroad_title': 'Concrete Estimating Template — Contractor Bid Calculator for Excel & '
                   'Google Sheets',
  'summary': 'Seven-tab Concrete estimating workbook for Excel & Google Sheets — burdened '
             'labor cost, overhead recovery, true margin pricing, client proposal and job '
             'costing.',
  'price': 89,
  'url': 'https://thecalmdeskco.gumroad.com/l/concrete-estimating-template',
  'product_id': 'jj8eFhp5eKVc1-FbLtXjmw==',
  'category': 'business-and-money/accounting',
  'tags': ['concrete',
           'concrete bids',
           'bid calculator',
           'estimating',
           'contractor',
           'construction',
           'excel template',
           'google sheets',
           'job costing',
           'labor burden',
           'spreadsheet',
           'digital download'],
  'tabs': ['Start Here',
           'Rates',
           'Price Book',
           'Estimate',
           'Bid Summary',
           'Proposal',
           'Job Costing'],
  'functions': ['CEILING', 'IF', 'IFERROR', 'MAX', 'ROUND', 'SUM', 'VLOOKUP'],
  'notable_functions': [],
  'xlsx': '/Users/allanninal/Projects/gumroad-products/trades/concrete-bid-calculator/Concrete-Contractor-Bid-Calculator.xlsx',
  'cover': '/Users/allanninal/Projects/gumroad-products/trades/concrete-bid-calculator/cover.png',
  'created_at': '2026-08-21T14:40:31Z',
  'gumroad_name': 'Concrete Estimating Template — Contractor Bid Calculator for Excel & Google '
                  'Sheets',
  'sales_count': 0},
 {'key': 'electrical-bid-calculator',
  'line': 'trades',
  'gumroad_title': 'Electrical Estimating Template — Contractor Bid Calculator for Excel & '
                   'Google Sheets',
  'summary': 'Seven-tab Electrical estimating workbook for Excel & Google Sheets — burdened '
             'labor cost, overhead recovery, true margin pricing, client proposal and job '
             'costing.',
  'price': 89,
  'url': 'https://thecalmdeskco.gumroad.com/l/electrical-estimating-template',
  'product_id': 'AkofHb47-sm6KGMGBQB7ZA==',
  'category': 'business-and-money/accounting',
  'tags': ['electrical',
           'electrical bids',
           'bid calculator',
           'estimating',
           'contractor',
           'construction',
           'excel template',
           'google sheets',
           'job costing',
           'labor burden',
           'spreadsheet',
           'digital download'],
  'tabs': ['Start Here',
           'Rates',
           'Price Book',
           'Estimate',
           'Bid Summary',
           'Proposal',
           'Job Costing'],
  'functions': ['CEILING', 'IF', 'IFERROR', 'MAX', 'ROUND', 'SUM', 'VLOOKUP'],
  'notable_functions': [],
  'xlsx': '/Users/allanninal/Projects/gumroad-products/trades/electrical-bid-calculator/Electrical-Contractor-Bid-Calculator.xlsx',
  'cover': '/Users/allanninal/Projects/gumroad-products/trades/electrical-bid-calculator/cover.png',
  'created_at': '2026-08-21T14:39:04Z',
  'gumroad_name': 'Electrical Estimating Template — Contractor Bid Calculator for Excel & '
                  'Google Sheets',
  'sales_count': 0},
 {'key': 'equipment-fleet-cost-per-hour',
  'line': 'fleet',
  'gumroad_title': 'Equipment Fleet Cost Per Hour — Excel Own vs Rent, Break-Even & Charge-Out '
                   'Rate',
  'summary': 'Eight-tab equipment cost-per-hour workbook for Excel & Google Sheets — ownership '
             'and operating cost, charge-out rate, own-vs-rent break-even hours and a '
             'utilisation curve.',
  'price': 89,
  'url': 'https://thecalmdeskco.gumroad.com/l/equipment-cost-per-hour-calculator',
  'product_id': 'XMgqOJkX5DsSyvG50jnAjw==',
  'category': 'business-and-money/accounting',
  'tags': ['equipment cost',
           'cost per hour',
           'own vs rent',
           'construction',
           'fleet',
           'heavy equipment',
           'excel template',
           'google sheets',
           'contractor',
           'utilisation',
           'break even',
           'digital download'],
  'tabs': ['Start Here',
           'Rates',
           'Fleet',
           'Ownership Cost',
           'Operating Cost',
           'Rate Build-Up',
           'Own vs Rent',
           'Utilisation',
           'How It Works'],
  'functions': ['AVERAGE', 'COUNTIF', 'IF', 'IFERROR', 'SUM', 'SUMIF'],
  'notable_functions': [],
  'xlsx': '/Users/allanninal/Projects/gumroad-products/fleet/equipment-fleet-cost-per-hour/Equipment-Fleet-Cost-Per-Hour-Own-vs-Rent.xlsx',
  'cover': '/Users/allanninal/Projects/gumroad-products/fleet/equipment-fleet-cost-per-hour/cover.png',
  'created_at': '2026-08-23T00:58:15Z',
  'gumroad_name': 'Equipment Fleet Cost Per Hour — Excel Own vs Rent, Break-Even & Charge-Out '
                  'Rate',
  'sales_count': 0},
 {'key': 'federal-grant-budget-mtdc',
  'line': 'grants',
  'gumroad_title': 'Federal Grant Budget & MTDC Indirect Cost Calculator — Excel & Google '
                   'Sheets, De Minimis + NICRA',
  'summary': 'Builds the MTDC base properly — subaward cap per period not per year, equipment '
             'tested per unit, caps applied as margins. De minimis vs NICRA. Excel + Google '
             'Sheets.',
  'price': 89,
  'url': 'https://thecalmdeskco.gumroad.com/l/federal-grant-budget-mtdc-indirect-cost-calculator',
  'product_id': 'RcxCVj5gAGnEiM-dFT90EA==',
  'category': 'business-and-money/accounting',
  'tags': ['grant budget',
           'nonprofit',
           'mtdc',
           'indirect cost',
           'uniform guidance',
           'grant writing',
           'budget template',
           '2 cfr 200'],
  'tabs': ['Start Here',
           'Setup',
           'Personnel',
           'Non-Personnel',
           'Subawards',
           'Budget by Year',
           'Indirect Comparison',
           'Cost Share',
           'Checks',
           'How It Works'],
  'functions': ['ABS',
                'AND',
                'COUNTIF',
                'IF',
                'IFERROR',
                'MAX',
                'MIN',
                'OR',
                'SUM',
                'SUMPRODUCT',
                'VLOOKUP'],
  'notable_functions': [],
  'xlsx': '/Users/allanninal/Projects/gumroad-products/grants/federal-grant-budget-mtdc/Federal-Grant-Budget-MTDC-Indirect-Cost-Workbook.xlsx',
  'cover': '/Users/allanninal/Projects/gumroad-products/grants/federal-grant-budget-mtdc/cover.png',
  'created_at': '2026-08-24T05:02:05Z',
  'gumroad_name': 'Federal Grant Budget & MTDC Indirect Cost Calculator — Excel & Google '
                  'Sheets, De Minimis + NICRA',
  'sales_count': 0},
 {'key': 'hvac-bid-calculator',
  'line': 'trades',
  'gumroad_title': 'HVAC Estimating Template — Contractor Bid Calculator for Excel & Google '
                   'Sheets',
  'summary': 'Seven-tab HVAC estimating workbook for Excel & Google Sheets — burdened labor '
             'cost, overhead recovery, true margin pricing, client proposal and job costing.',
  'price': 89,
  'url': 'https://thecalmdeskco.gumroad.com/l/hvac-estimating-template',
  'product_id': 'Nfk4XZhkgH8NivcDxRqLpg==',
  'category': 'business-and-money/accounting',
  'tags': ['hvac',
           'hvac bids',
           'bid calculator',
           'estimating',
           'contractor',
           'construction',
           'excel template',
           'google sheets',
           'job costing',
           'labor burden',
           'spreadsheet',
           'digital download'],
  'tabs': ['Start Here',
           'Rates',
           'Price Book',
           'Estimate',
           'Bid Summary',
           'Proposal',
           'Job Costing'],
  'functions': ['CEILING', 'IF', 'IFERROR', 'MAX', 'ROUND', 'SUM', 'VLOOKUP'],
  'notable_functions': [],
  'xlsx': '/Users/allanninal/Projects/gumroad-products/trades/hvac-bid-calculator/HVAC-Contractor-Bid-Calculator.xlsx',
  'cover': '/Users/allanninal/Projects/gumroad-products/trades/hvac-bid-calculator/cover.png',
  'created_at': '2026-08-21T14:40:11Z',
  'gumroad_name': 'HVAC Estimating Template — Contractor Bid Calculator for Excel & Google '
                  'Sheets',
  'sales_count': 0},
 {'key': 'landscaping-bid-calculator',
  'line': 'trades',
  'gumroad_title': 'Landscaping Estimating Template — Contractor Bid Calculator for Excel & '
                   'Google Sheets',
  'summary': 'Seven-tab Landscaping estimating workbook for Excel & Google Sheets — burdened '
             'labor cost, overhead recovery, true margin pricing, client proposal and job '
             'costing.',
  'price': 89,
  'url': 'https://thecalmdeskco.gumroad.com/l/landscaping-estimating-template',
  'product_id': '11pnxmWb8Tki_5-IeIKBgg==',
  'category': 'business-and-money/accounting',
  'tags': ['landscaping',
           'landscaping bids',
           'bid calculator',
           'estimating',
           'contractor',
           'construction',
           'excel template',
           'google sheets',
           'job costing',
           'labor burden',
           'spreadsheet',
           'digital download'],
  'tabs': ['Start Here',
           'Rates',
           'Price Book',
           'Estimate',
           'Bid Summary',
           'Proposal',
           'Job Costing'],
  'functions': ['CEILING', 'IF', 'IFERROR', 'MAX', 'ROUND', 'SUM', 'VLOOKUP'],
  'notable_functions': [],
  'xlsx': '/Users/allanninal/Projects/gumroad-products/trades/landscaping-bid-calculator/Landscaping-Contractor-Bid-Calculator.xlsx',
  'cover': '/Users/allanninal/Projects/gumroad-products/trades/landscaping-bid-calculator/cover.png',
  'created_at': '2026-08-21T14:40:21Z',
  'gumroad_name': 'Landscaping Estimating Template — Contractor Bid Calculator for Excel & '
                  'Google Sheets',
  'sales_count': 0},
 {'key': 'progress-billing-schedule-of-values',
  'line': 'billing',
  'gumroad_title': 'Progress Billing & Schedule of Values Workbook — Excel Payment Application '
                   'with Retainage',
  'summary': 'Eight-tab progress billing workbook for Excel & Google Sheets — schedule of '
             'values, stored materials, retainage with reduction, change order log and six '
             'pre-submission controls.',
  'price': 89,
  'url': 'https://thecalmdeskco.gumroad.com/l/progress-billing-schedule-of-values',
  'product_id': 'W0UHWjXnSy-nlOIi9aDa4Q==',
  'category': 'business-and-money/accounting',
  'tags': ['progress billing',
           'schedule of values',
           'construction',
           'contractor',
           'retainage',
           'payment application',
           'excel template',
           'google sheets',
           'billing',
           'accounting',
           'change orders',
           'digital download'],
  'tabs': ['Start Here',
           'Schedule of Values',
           'Application',
           'Summary',
           'Change Orders',
           'Retainage',
           'Checks',
           'How It Works'],
  'functions': ['ABS',
                'AND',
                'COUNTIF',
                'IF',
                'IFERROR',
                'ISNUMBER',
                'MAX',
                'SUM',
                'SUMIF',
                'SUMPRODUCT'],
  'notable_functions': [],
  'xlsx': '/Users/allanninal/Projects/gumroad-products/billing/progress-billing-schedule-of-values/Progress-Billing-Schedule-of-Values-Workbook.xlsx',
  'cover': '/Users/allanninal/Projects/gumroad-products/billing/progress-billing-schedule-of-values/cover.png',
  'created_at': '2026-08-22T17:44:05Z',
  'gumroad_name': 'Progress Billing & Schedule of Values Workbook — Excel Payment Application '
                  'with Retainage',
  'sales_count': 0},
 {'key': 'roofing-bid-calculator',
  'line': 'trades',
  'gumroad_title': 'Roofing Estimating Template — Contractor Bid Calculator for Excel & Google '
                   'Sheets',
  'summary': 'Seven-tab Roofing estimating workbook for Excel & Google Sheets — burdened labor '
             'cost, overhead recovery, true margin pricing, client proposal and job costing.',
  'price': 89,
  'url': 'https://thecalmdeskco.gumroad.com/l/roofing-estimating-template',
  'product_id': 'E96Zr4lFueKNdDacPs_31A==',
  'category': 'business-and-money/accounting',
  'tags': ['roofing',
           'roofing bids',
           'bid calculator',
           'estimating',
           'contractor',
           'construction',
           'excel template',
           'google sheets',
           'job costing',
           'labor burden',
           'spreadsheet',
           'digital download'],
  'tabs': ['Start Here',
           'Rates',
           'Price Book',
           'Estimate',
           'Bid Summary',
           'Proposal',
           'Job Costing'],
  'functions': ['CEILING', 'IF', 'IFERROR', 'MAX', 'ROUND', 'SUM', 'VLOOKUP'],
  'notable_functions': [],
  'xlsx': '/Users/allanninal/Projects/gumroad-products/trades/roofing-bid-calculator/Roofing-Contractor-Bid-Calculator.xlsx',
  'cover': '/Users/allanninal/Projects/gumroad-products/trades/roofing-bid-calculator/cover.png',
  'created_at': '2026-08-21T14:40:39Z',
  'gumroad_name': 'Roofing Estimating Template — Contractor Bid Calculator for Excel & Google '
                  'Sheets',
  'sales_count': 0},
 {'key': 'landed-cost-duty-calculator',
  'line': 'importing',
  'gumroad_title': 'Landed Cost Calculator — Excel & Google Sheets Import Duty, Tariff & '
                   'Freight Allocation Tool',
  'summary': 'Seven-tab landed cost workbook for Excel & Google Sheets — multi-currency, '
             'FOB/CIF duty, stacked tariffs, freight allocation across SKUs, true per-unit '
             'COGS and break-even repricing.',
  'price': 79,
  'url': 'https://thecalmdeskco.gumroad.com/l/landed-cost-calculator',
  'product_id': 'gtrEL8tLGhYDObF48aZ_vg==',
  'category': 'business-and-money/accounting',
  'tags': ['landed cost',
           'import duty',
           'tariff calculator',
           'customs',
           'importing',
           'excel template',
           'google sheets',
           'ecommerce',
           'amazon fba',
           'cogs',
           'freight',
           'digital download'],
  'tabs': ['Start Here',
           'Shipment',
           'SKUs',
           'Landed Cost',
           'Repricing',
           'Scenario',
           'Duty Reference'],
  'functions': ['IF', 'IFERROR', 'MAX', 'MIN', 'SUM', 'SUMPRODUCT', 'TEXT', 'VLOOKUP'],
  'notable_functions': [],
  'xlsx': '/Users/allanninal/Projects/gumroad-products/importing/landed-cost-duty-calculator/Landed-Cost-Duty-Tariff-Calculator.xlsx',
  'cover': '/Users/allanninal/Projects/gumroad-products/importing/landed-cost-duty-calculator/cover.png',
  'created_at': '2026-08-22T15:17:13Z',
  'gumroad_name': 'Landed Cost Calculator — Excel & Google Sheets Import Duty, Tariff & '
                  'Freight Allocation Tool',
  'sales_count': 0},
 {'key': 'spc-control-chart-capability-workbook',
  'line': 'spc',
  'gumroad_title': 'SPC Control Chart & Process Capability Workbook — Excel, Cp/Cpk, Gage R&R, '
                   'Xbar-R, I-MR',
  'summary': 'Eight-tab SPC workbook for Excel & Google Sheets — Xbar-R, I-MR and p-charts '
             'with Western Electric rules, Cp/Cpk/Pp/Ppk with PPM, and an AIAG Gage R&R study. '
             'No add-in.',
  'price': 79,
  'url': 'https://thecalmdeskco.gumroad.com/l/spc-control-chart-cpk-workbook',
  'product_id': 'JFerZ4AqaJqYbtNsYeolCg==',
  'category': 'business-and-money/entrepreneurship',
  'tags': ['spc',
           'control chart',
           'process capability',
           'cpk',
           'gage r&r',
           'quality',
           'six sigma',
           'manufacturing',
           'excel template',
           'google sheets',
           'lean',
           'digital download'],
  'tabs': ['Start Here',
           'Constants',
           'Xbar-R',
           'I-MR',
           'p-Chart',
           'Capability',
           'Gage R&R',
           'How It Works'],
  'functions': ['ABS',
                'AVERAGE',
                'COUNT',
                'COUNTIF',
                'IF',
                'IFERROR',
                'INT',
                'MAX',
                'MIN',
                'NORMSDIST',
                'OR',
                'SQRT',
                'STDEV',
                'SUM',
                'VLOOKUP'],
  'notable_functions': ['NORMSDIST', 'STDEV'],
  'xlsx': '/Users/allanninal/Projects/gumroad-products/spc/spc-control-chart-capability-workbook/SPC-Control-Chart-Capability-Gage-RR-Workbook.xlsx',
  'cover': '/Users/allanninal/Projects/gumroad-products/spc/spc-control-chart-capability-workbook/cover.png',
  'created_at': '2026-08-22T16:07:59Z',
  'gumroad_name': 'SPC Control Chart & Process Capability Workbook — Excel, Cp/Cpk, Gage R&R, '
                  'Xbar-R, I-MR',
  'sales_count': 0},
 {'key': 'design-of-experiments-workbook',
  'line': 'doe',
  'gumroad_title': 'Design of Experiments Workbook — Excel 2^4 Factorial, Effects, ANOVA & '
                   "Lenth's Method",
  'summary': 'Seven-tab DOE workbook for Excel & Google Sheets — full 2^4 factorial with '
             "effects, sums of squares, normal plot, Lenth's PSE, ANOVA, curvature test and a "
             'prediction model. No add-in.',
  'price': 69,
  'url': 'https://thecalmdeskco.gumroad.com/l/design-of-experiments-excel',
  'product_id': 'Am5D-iY99DY0P2XOR2-lyw==',
  'category': 'business-and-money/entrepreneurship',
  'tags': ['experiment design',
           'doe',
           'factorial',
           'six sigma',
           'statistics',
           'process improvement',
           'excel template',
           'google sheets',
           'quality',
           'engineering',
           'anova',
           'digital download'],
  'tabs': ['Start Here', 'Design', 'Effects', 'ANOVA', 'Normal Plot', 'Model', 'How It Works'],
  'functions': ['ABS',
                'AVERAGE',
                'COUNT',
                'COUNTIF',
                'FDIST',
                'IF',
                'IFERROR',
                'INT',
                'MAX',
                'MEDIAN',
                'NORMSINV',
                'RANK',
                'SUM',
                'SUMIF',
                'SUMPRODUCT',
                'TINV'],
  'notable_functions': ['FDIST', 'MEDIAN', 'NORMSINV', 'RANK', 'TINV'],
  'xlsx': '/Users/allanninal/Projects/gumroad-products/doe/design-of-experiments-workbook/Design-of-Experiments-2k-Factorial-Workbook.xlsx',
  'cover': '/Users/allanninal/Projects/gumroad-products/doe/design-of-experiments-workbook/cover.png',
  'created_at': '2026-08-22T16:56:29Z',
  'gumroad_name': 'Design of Experiments Workbook — Excel 2^4 Factorial, Effects, ANOVA & '
                  "Lenth's Method",
  'sales_count': 0},
 {'key': 'monte-carlo-simulation-workbook',
  'line': 'montecarlo',
  'gumroad_title': 'Monte Carlo Simulation Workbook — Excel & Google Sheets Risk Analysis, No '
                   'Add-In Required',
  'summary': 'Eight-tab Monte Carlo engine for Excel & Google Sheets — 12 variables, 1,000 '
             'trials, five distributions, correlated inputs, percentiles, S-curve and '
             'sensitivity. No add-in, no macros.',
  'price': 69,
  'url': 'https://thecalmdeskco.gumroad.com/l/monte-carlo-simulation-excel',
  'product_id': '5zHsok08CbKzj71gCu2J1A==',
  'category': 'business-and-money/entrepreneurship',
  'tags': ['monte carlo',
           'simulation',
           'risk analysis',
           'project management',
           'excel template',
           'google sheets',
           'forecasting',
           'statistics',
           'cost estimating',
           'sensitivity',
           'spreadsheet',
           'digital download'],
  'tabs': ['Start Here',
           'Variables',
           'Trials',
           'Results',
           'Sensitivity',
           'Compare',
           'Presets',
           'How It Works'],
  'functions': ['AVERAGE',
                'CORREL',
                'COUNT',
                'COUNTIF',
                'COUNTIFS',
                'EXP',
                'IF',
                'IFERROR',
                'MAX',
                'MEDIAN',
                'MIN',
                'NORMINV',
                'NORMSDIST',
                'NORMSINV',
                'PERCENTILE',
                'RAND',
                'RANK',
                'SQRT',
                'STDEV',
                'SUM'],
  'notable_functions': ['CORREL',
                        'MEDIAN',
                        'NORMINV',
                        'NORMSDIST',
                        'NORMSINV',
                        'PERCENTILE',
                        'RAND',
                        'RANK',
                        'STDEV'],
  'xlsx': '/Users/allanninal/Projects/gumroad-products/montecarlo/monte-carlo-simulation-workbook/Monte-Carlo-Simulation-Workbook.xlsx',
  'cover': '/Users/allanninal/Projects/gumroad-products/montecarlo/monte-carlo-simulation-workbook/cover.png',
  'created_at': '2026-08-22T15:32:42Z',
  'gumroad_name': 'Monte Carlo Simulation Workbook — Excel & Google Sheets Risk Analysis, No '
                  'Add-In Required',
  'sales_count': 0},
 {'key': 'recipe-costing-menu-engineering',
  'line': 'kitchen',
  'gumroad_title': 'Recipe Costing & Menu Engineering Workbook — Excel, Plate Cost, Yield % & '
                   'Menu Matrix',
  'summary': 'Eight-tab recipe costing workbook for Excel & Google Sheets — yield-adjusted '
             'ingredient costs, sub-recipes, plate cost, food cost %, and the '
             'Star/Plowhorse/Puzzle/Dog menu matrix.',
  'price': 59,
  'url': 'https://thecalmdeskco.gumroad.com/l/recipe-costing-menu-engineering',
  'product_id': 'ThC6_nAlDL7kEl8RQezybw==',
  'category': 'business-and-money/entrepreneurship',
  'tags': ['recipe costing',
           'menu engineering',
           'restaurant',
           'food cost',
           'plate cost',
           'excel template',
           'google sheets',
           'hospitality',
           'chef',
           'cafe',
           'catering',
           'digital download'],
  'tabs': ['Start Here',
           'Ingredients',
           'Sub-Recipes',
           'Recipes',
           'Menu',
           'Menu Engineering',
           'Price Finder',
           'How It Works'],
  'functions': ['COUNTIF', 'IF', 'IFERROR', 'MAX', 'SUM', 'SUMIF', 'SUMPRODUCT', 'VLOOKUP'],
  'notable_functions': [],
  'xlsx': '/Users/allanninal/Projects/gumroad-products/kitchen/recipe-costing-menu-engineering/Recipe-Costing-Menu-Engineering-Workbook.xlsx',
  'cover': '/Users/allanninal/Projects/gumroad-products/kitchen/recipe-costing-menu-engineering/cover.png',
  'created_at': '2026-08-22T16:30:38Z',
  'gumroad_name': 'Recipe Costing & Menu Engineering Workbook — Excel, Plate Cost, Yield % & '
                  'Menu Matrix',
  'sales_count': 0}]

BY_KEY = {p['key']: p for p in PRODUCTS}
