#!/usr/bin/env python3
"""Featured-image spec, one per guide. Consumed by guide_covers.py.

`before` and `after` are the actual values from that guide, not illustrations. Keep them
short — anything much past ~18 characters stops fitting the panel at 46pt mono, and the
generator does not shrink to fit, it just runs wide.

For the guides where nothing is literally destroyed (the formula ones), the pair reads as
"what you wrote" and "what you got", which is the same idea.
"""

COVERS = [
 # --- A: when Excel changes your data ---------------------------------------
 dict(slug="excel-leading-zeros-disappear", kicker="Data integrity",
      headline="Excel deletes the zero at the front of your numbers",
      before="01234", after="1234",
      caption="Postcodes, SKUs and employee IDs, read as numbers. Formatting the column afterwards cannot bring the zero back."),
 dict(slug="excel-csv-utf8-mojibake", kicker="Data integrity",
      headline="Accented characters arrive as nonsense",
      before="Niñal", after="NiÃ±al",
      caption="A UTF-8 file read as Windows-1252. The file is fine — set File Origin to 65001 on import."),
 dict(slug="excel-converts-text-to-dates", kicker="Data integrity",
      headline="Excel turns part numbers into dates",
      before="SEP1", after="01-Sep",
      caption="Converted the moment it arrives, and the original text is not kept anywhere. This one is not reversible."),
 dict(slug="excel-vlookup-non-breaking-space", kicker="Data integrity",
      headline="VLOOKUP says #N/A but the value is right there",
      before='"Smith"', after='"Smith·"',
      caption="A non-breaking space from a web paste. TRIM does not remove it, which is why the second attempt fails too."),
 dict(slug="excel-csv-all-in-column-a", kicker="Data integrity",
      headline="The whole CSV opened into one column",
      before="a; b; c", after="one cell",
      caption="The file was written with a different delimiter from the one your Excel expects. Fix it per file, not in Windows."),
 dict(slug="excel-numbers-stored-as-text", kicker="Data integrity",
      headline="SUM is quietly ignoring half your column",
      before="SUM(…)", after="0",
      caption="Numbers stored as text are skipped without any warning. The dangerous case is the total that is wrong but plausible."),
 dict(slug="excel-scientific-notation-barcodes", kicker="Data integrity",
      headline="Your barcode became 1.23E+14",
      before="…345678", after="…340000",
      caption="Scientific notation is only a display. The 15-digit limit behind it replaces the rest with zeros, permanently."),

 # --- B: formulas that do not behave as they read ---------------------------
 dict(slug="excel-absolute-relative-references", kicker="Formulas",
      headline="The formula breaks the moment you drag it down",
      before="=B2*$F$1", after="=B2*F9",
      caption="References are a direction, not an address. The $ is what pins the part that must not move."),
 dict(slug="excel-formulas-not-updating", kicker="Formulas",
      headline="Formulas showing yesterday's answers",
      before="Automatic", after="Manual",
      caption="Calculation mode lives in the workbook, and the first file opened sets it for every file after it."),
 dict(slug="excel-unique-values-list", kicker="Formulas",
      headline="Getting the distinct values out of a column",
      before="UNIQUE()", after="#NAME?",
      caption="One formula on Microsoft 365, and three methods that work on every older version without touching your data."),
 dict(slug="excel-compare-two-lists", kicker="Formulas",
      headline="What is in this list but not the other",
      before="in both", after="MISSING",
      caption="One COUNTIF, run in both directions. The trap is what counts as a match when the data is not clean."),
 dict(slug="excel-sumifs-vs-pivot-table", kicker="Formulas",
      headline="A total for each category",
      before="SUMIFS", after="Pivot",
      caption="Both give the same numbers. One lives in your report layout; the other owns its own block and needs refreshing."),
 dict(slug="excel-join-two-sheets-lookup", kicker="Formulas",
      headline="Pulling data from one sheet into another",
      before="XLOOKUP", after="VLOOKUP",
      caption="VLOOKUP names its return column by position, so an inserted column changes the answer without erroring."),
 dict(slug="excel-sum-visible-rows-only", kicker="Formulas",
      headline="The total does not change when you filter",
      before="SUBTOTAL", after="SUM",
      caption="SUM has no idea a filter exists. It keeps totalling the rows you can no longer see."),
 dict(slug="excel-return-blank-not-zero", kicker="Formulas",
      headline="A blank that is not really blank",
      before="empty", after='""',
      caption="An empty string is text. ISBLANK is false, COUNTA counts it, and a chart plots it as zero."),
 dict(slug="excel-count-functions-explained", kicker="Formulas",
      headline="Which COUNT function you actually want",
      before="COUNTA", after="COUNT",
      caption="They disagree on purpose, and the gap between them is the fastest way to find numbers stored as text."),
 dict(slug="excel-negative-number-squared", kicker="Formulas",
      headline="Excel says minus three squared is positive nine",
      before="-(3^2) = -9", after="-3^2 = 9",
      caption="Excel binds the unary minus before the exponent. In a present-value formula, the sign flips silently."),
 dict(slug="excel-apply-formula-entire-column", kicker="Formulas",
      headline="Getting one formula into ten thousand rows",
      before="Ctrl+D", after="drag…",
      caption="Four methods. Only one of them keeps working for the rows somebody adds next month."),

 # --- C: cleaning a real export ---------------------------------------------
 dict(slug="clean-bank-statement-export-excel", kicker="Worked example",
      headline="Cleaning a bank statement so it reconciles",
      before="-500.00", after="(500)",
      caption="Accounting negatives read as text. Convert without handling them and the balance is out by twice the debits."),
 dict(slug="clean-student-list-excel", kicker="Worked example",
      headline="Cleaning a class list so the IDs still match",
      before="004512", after="4512",
      caption="Student numbers are zero-padded. Lose the padding and every student under 1000 drops out of the merge."),
 dict(slug="clean-inventory-sku-export-excel", kicker="Worked example",
      headline="Cleaning a product export without breaking the SKUs",
      before="0041-2", after="04-Jan",
      caption="A catalogue is mostly identifier columns, which is exactly what Excel handles worst. Three failures in one file."),
 dict(slug="clean-crm-contact-export-excel", kicker="Worked example",
      headline="Cleaning a contact list before you send anything",
      before="0 duplicates", after="sent twice",
      caption="Deduplication compares values exactly as stored, so invisible characters hide the duplicates it reports as absent."),
 dict(slug="clean-payroll-timesheet-export-excel", kicker="Worked example",
      headline="Cleaning a timesheet so the hours add up",
      before="37:30", after="13:30",
      caption="Excel stores time as a fraction of a day, so totals roll over at 24 hours unless the format says otherwise."),

 # --- D: Power Query ---------------------------------------------------------
 dict(slug="excel-power-query-unpivot", kicker="Power Query",
      headline="A column for every month, and nothing works",
      before="12 columns", after="3 columns",
      caption="The month is in the heading, so no formula can read it. Unpivot turns headings into data — and it repeats next month."),
 dict(slug="excel-power-query-parameter-cell", kicker="Power Query",
      headline="Make a query read a date from a cell",
      before="=B1", after="not a cell",
      caption="Power Query has no idea what a cell is. Load the cell as a one-row table and drill down to the value."),
 dict(slug="excel-power-query-combine-files-folder", kicker="Power Query",
      headline="Forty files that all need the same treatment",
      before="1 folder", after="40 opens",
      caption="Point a query at the folder. Clean the sample once and every file is cleaned, including the one you add next month."),
 dict(slug="excel-power-query-merge-join", kicker="Power Query",
      headline="A proper join, not fifty thousand lookups",
      before="1 merge", after="50,000 =",
      caption="Inner, left, right, full outer and anti joins by name. The anti join is the one no lookup formula can do."),
 dict(slug="excel-power-query-refresh-load-settings", kicker="Power Query",
      headline="A workbook full of sheets you did not ask for",
      before="1 sheet", after="6 sheets",
      caption="Enable Load decides whether a query writes a sheet and stores a copy. That copy is usually why the file is 40MB."),
 dict(slug="excel-power-query-vs-power-pivot", kicker="Power Query",
      headline="Power Query or Power Pivot — which do you need?",
      before="clean it", after="model it",
      caption="One shapes data on the way in, the other relates tables once it is there. Learn Power Query first."),

 # --- E: dynamic arrays and text ---------------------------------------------
 dict(slug="excel-spill-error", kicker="Dynamic arrays",
      headline="One formula, many cells, and no room",
      before="empty", after="#SPILL!",
      caption="Something is in the way — usually a space typed years ago, or a merged cell you cannot see."),
 dict(slug="excel-filter-function", kicker="Dynamic arrays",
      headline="Every row that matches, not just the first",
      before="(blank)", after="0",
      caption="FILTER returns cell values, and an empty cell read as a value is zero. That is the trap everyone hits first."),
 dict(slug="excel-sort-sortby", kicker="Dynamic arrays",
      headline="A sorted list that stays sorted",
      before="SORT()", after="re-sort",
      caption="Ribbon sorting rearranges your data and has to be redone. A formula makes a copy that keeps itself in order."),
 dict(slug="excel-lambda-named-functions", kicker="Dynamic arrays",
      headline="Your own function, without a macro",
      before=".xlsx", after=".xlsm",
      caption="VBA turns the file into .xlsm and may be blocked at work. LAMBDA does the same job and stays a plain spreadsheet."),
 dict(slug="excel-byrow-bycol", kicker="Dynamic arrays",
      headline="One answer per row, no helper column",
      before="1 formula", after="fill down",
      caption="A helper column that nobody filled down is the quiet cause of a total that is wrong at the bottom."),
 dict(slug="excel-regex-functions", kicker="Text and regex",
      headline="Excel finally has regular expressions",
      before="REGEXTEST", after="needs VBA",
      caption="Added in 2024. Nearly everything written about regex in Excel predates the functions and still tells you to write a macro."),
 dict(slug="excel-extract-numbers-from-text", kicker="Text and regex",
      headline="The number out of Order 4471 — urgent",
      before="-12.50", after="1250",
      caption="Stripping everything that is not a digit takes the decimal point and the minus sign with it."),
 dict(slug="excel-textsplit-functions", kicker="Text and regex",
      headline="Splitting a column without doing it again",
      before="formula", after="one-off",
      caption="Text to Columns runs once, on the rows that existed at the time. Rows added later sit unsplit at the bottom."),

 # --- F: formatting, lookups, recovery ---------------------------------------
 dict(slug="excel-conditional-format-another-cell", kicker="Conditional formatting",
      headline="Colour this cell by what that cell says",
      before="=$C2", after="=C2",
      caption="The rule is written for the top-left cell and walked across the rest. One dollar sign decides whether it works."),
 dict(slug="excel-highlight-duplicates", kicker="Conditional formatting",
      headline="Which of these appear more than once?",
      before="extras", after="all copies",
      caption="The built-in rule colours the original too. When you are deciding what to delete, that is the wrong answer."),
 dict(slug="excel-conditional-format-ranges-changing", kicker="Conditional formatting",
      headline="One rule has turned into forty",
      before="1 rule", after="40 rules",
      caption="Copying cells inside a formatted range brings a copy of the rule. Excel keeps both when it cannot merge them."),
 dict(slug="excel-last-match-lookup", kicker="Lookups",
      headline="The most recent one, not the first one",
      before="latest", after="oldest",
      caption="VLOOKUP scans from the top and stops at the first hit. On a price history that is the price from two years ago."),
 dict(slug="excel-last-non-empty-cell", kicker="Lookups",
      headline="The latest reading, wherever the column ends",
      before="last value", after="2nd to last",
      caption="Counting rows breaks the moment there is a gap. Search for the last value instead of the last position."),
 dict(slug="excel-sheet-name-in-cell", kicker="Lookups",
      headline="Put the tab's name in the heading",
      before="January", after="(blank)",
      caption="CELL returns nothing until the file has been saved, and reports the wrong tab if you omit the cell reference."),
 dict(slug="excel-column-number-to-letter", kicker="Lookups",
      headline="Column 27 is AA, and 703 is AAA",
      before="AA", after="$AA$1",
      caption="It looks like base 26 and is not, because there is no zero digit. Let ADDRESS do it rather than the arithmetic."),
 dict(slug="excel-recover-unsaved-file", kicker="Files and recovery",
      headline="Closed without saving, three hours of work",
      before="4 days", after="10 min",
      caption="Excel keeps copies of unsaved work, but only for a while and only if the settings allowed it. Look before doing anything else."),
 dict(slug="excel-broken-external-links", kicker="Files and recovery",
      headline="A link to a file you deleted years ago",
      before="4 places", after="Break Links",
      caption="Break Links only reaches cell formulas. Names, validation, formatting and charts each hide one where it cannot see."),
]
