#!/usr/bin/env python3
"""Featured-image spec, one per guide. Consumed by guide_covers.py.

`before` and `after` are the actual values from that guide, not illustrations. Keep them
short — anything much past ~18 characters stops fitting the panel at 46pt mono, and the
generator does not shrink to fit, it just runs wide.

For the guides where nothing is literally destroyed (the formula ones), the pair reads as
"what you wrote" and "what you got", which is the same idea.
"""

COVERS = [
 # --- A: when Excel changes your data ---------------------------------------
 dict(slug="excel-leading-zeros-disappear", kicker="Data integrity",
      headline="Excel deletes the zero at the front of your numbers",
      before="01234", after="1234",
      caption="Postcodes, SKUs and employee IDs, read as numbers. Formatting the column afterwards cannot bring the zero back."),
 dict(slug="excel-csv-utf8-mojibake", kicker="Data integrity",
      headline="Accented characters arrive as nonsense",
      before="Niñal", after="NiÃ±al",
      caption="A UTF-8 file read as Windows-1252. The file is fine — set File Origin to 65001 on import."),
 dict(slug="excel-converts-text-to-dates", kicker="Data integrity",
      headline="Excel turns part numbers into dates",
      before="SEP1", after="01-Sep",
      caption="Converted the moment it arrives, and the original text is not kept anywhere. This one is not reversible."),
 dict(slug="excel-vlookup-non-breaking-space", kicker="Data integrity",
      headline="VLOOKUP says #N/A but the value is right there",
      before='"Smith"', after='"Smith·"',
      caption="A non-breaking space from a web paste. TRIM does not remove it, which is why the second attempt fails too."),
 dict(slug="excel-csv-all-in-column-a", kicker="Data integrity",
      headline="The whole CSV opened into one column",
      before="a; b; c", after="one cell",
      caption="The file was written with a different delimiter from the one your Excel expects. Fix it per file, not in Windows."),
 dict(slug="excel-numbers-stored-as-text", kicker="Data integrity",
      headline="SUM is quietly ignoring half your column",
      before="SUM(…)", after="0",
      caption="Numbers stored as text are skipped without any warning. The dangerous case is the total that is wrong but plausible."),
 dict(slug="excel-scientific-notation-barcodes", kicker="Data integrity",
      headline="Your barcode became 1.23E+14",
      before="…345678", after="…340000",
      caption="Scientific notation is only a display. The 15-digit limit behind it replaces the rest with zeros, permanently."),

 # --- B: formulas that do not behave as they read ---------------------------
 dict(slug="excel-absolute-relative-references", kicker="Formulas",
      headline="The formula breaks the moment you drag it down",
      before="=B2*$F$1", after="=B2*F9",
      caption="References are a direction, not an address. The $ is what pins the part that must not move."),
 dict(slug="excel-formulas-not-updating", kicker="Formulas",
      headline="Formulas showing yesterday's answers",
      before="Automatic", after="Manual",
      caption="Calculation mode lives in the workbook, and the first file opened sets it for every file after it."),
 dict(slug="excel-unique-values-list", kicker="Formulas",
      headline="Getting the distinct values out of a column",
      before="UNIQUE()", after="#NAME?",
      caption="One formula on Microsoft 365, and three methods that work on every older version without touching your data."),
 dict(slug="excel-compare-two-lists", kicker="Formulas",
      headline="What is in this list but not the other",
      before="in both", after="MISSING",
      caption="One COUNTIF, run in both directions. The trap is what counts as a match when the data is not clean."),
 dict(slug="excel-sumifs-vs-pivot-table", kicker="Formulas",
      headline="A total for each category",
      before="SUMIFS", after="Pivot",
      caption="Both give the same numbers. One lives in your report layout; the other owns its own block and needs refreshing."),
 dict(slug="excel-join-two-sheets-lookup", kicker="Formulas",
      headline="Pulling data from one sheet into another",
      before="XLOOKUP", after="VLOOKUP",
      caption="VLOOKUP names its return column by position, so an inserted column changes the answer without erroring."),
 dict(slug="excel-sum-visible-rows-only", kicker="Formulas",
      headline="The total does not change when you filter",
      before="SUBTOTAL", after="SUM",
      caption="SUM has no idea a filter exists. It keeps totalling the rows you can no longer see."),
 dict(slug="excel-return-blank-not-zero", kicker="Formulas",
      headline="A blank that is not really blank",
      before="empty", after='""',
      caption="An empty string is text. ISBLANK is false, COUNTA counts it, and a chart plots it as zero."),
 dict(slug="excel-count-functions-explained", kicker="Formulas",
      headline="Which COUNT function you actually want",
      before="COUNTA", after="COUNT",
      caption="They disagree on purpose, and the gap between them is the fastest way to find numbers stored as text."),
 dict(slug="excel-negative-number-squared", kicker="Formulas",
      headline="Excel says minus three squared is positive nine",
      before="-(3^2) = -9", after="-3^2 = 9",
      caption="Excel binds the unary minus before the exponent. In a present-value formula, the sign flips silently."),
 dict(slug="excel-apply-formula-entire-column", kicker="Formulas",
      headline="Getting one formula into ten thousand rows",
      before="Ctrl+D", after="drag…",
      caption="Four methods. Only one of them keeps working for the rows somebody adds next month."),

 # --- C: cleaning a real export ---------------------------------------------
 dict(slug="clean-bank-statement-export-excel", kicker="Worked example",
      headline="Cleaning a bank statement so it reconciles",
      before="-500.00", after="(500)",
      caption="Accounting negatives read as text. Convert without handling them and the balance is out by twice the debits."),
 dict(slug="clean-student-list-excel", kicker="Worked example",
      headline="Cleaning a class list so the IDs still match",
      before="004512", after="4512",
      caption="Student numbers are zero-padded. Lose the padding and every student under 1000 drops out of the merge."),
 dict(slug="clean-inventory-sku-export-excel", kicker="Worked example",
      headline="Cleaning a product export without breaking the SKUs",
      before="0041-2", after="04-Jan",
      caption="A catalogue is mostly identifier columns, which is exactly what Excel handles worst. Three failures in one file."),
 dict(slug="clean-crm-contact-export-excel", kicker="Worked example",
      headline="Cleaning a contact list before you send anything",
      before="0 duplicates", after="sent twice",
      caption="Deduplication compares values exactly as stored, so invisible characters hide the duplicates it reports as absent."),
 dict(slug="clean-payroll-timesheet-export-excel", kicker="Worked example",
      headline="Cleaning a timesheet so the hours add up",
      before="37:30", after="13:30",
      caption="Excel stores time as a fraction of a day, so totals roll over at 24 hours unless the format says otherwise."),
]
